"""Generate research.qmd and projects.qmd from the YAML files in data/.

Run automatically by Quarto (`pre-render: build.py` in _quarto.yml), or by hand:

    python build.py && quarto render

Content lives in data/*.yml so that adding a paper is a YAML edit rather than a
hand-written markup change. This script OWNS research.qmd and projects.qmd --
do not edit those two files by hand, they are overwritten on every render.

The emitted markup targets the class names defined in styles.scss:
  ol.entries > li  .entry-title  .entry-authors  .entry-venue  .entry-meta
  .badge-soft  .extras  .proj-period  .proj-client
"""
from __future__ import annotations

import html
import io
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(ROOT, "data")

BANNER = "<!-- GENERATED by build.py from data/{src} - do not edit by hand. -->"

# Order on the Research page. Research Grants is appended separately, last.
SECTIONS = [
    ("journal", "Publications"),
    ("wp", "Working Papers"),
    ("chapter", "Book Chapter"),
    ("report", "Non-peer-reviewed Report"),
    ("wip", "Work in Progress"),
    ("translation", "저·역서 (Translated Books)"),
]

# `detail` values that should render as a status badge rather than inline text
BADGES = {"submitted", "forthcoming"}


def load(name):
    with io.open(os.path.join(DATA, name), encoding="utf-8") as f:
        return yaml.safe_load(f)


def esc(text):
    return html.escape(str(text), quote=False)


def emphasise(text):
    """Render the *italic* spans authors write in YAML venue strings."""
    return re.sub(r"\*([^*]+)\*", r"<em>\1</em>", esc(text))


def authors_phrase(authors):
    if not authors:
        return ""
    names = [esc(a) for a in authors]
    if len(names) == 1:
        joined = names[0]
    elif len(names) == 2:
        joined = f"{names[0]} and {names[1]}"
    else:
        joined = ", ".join(names[:-1]) + f", and {names[-1]}"
    return f'<span class="entry-authors"> (with {joined})</span>'


def split_badge(detail):
    """Return (inline_detail, badge_text)."""
    if not detail:
        return None, None
    key = detail.strip().lower()
    if key in BADGES:
        return None, detail.strip()
    # e.g. "Forthcoming (2026)"
    m = re.match(r"^(forthcoming)\s*(\(.*\))$", detail.strip(), flags=re.I)
    if m:
        return m.group(2), m.group(1)
    return detail, None


def render_entry(e):
    title = esc(e["title"])
    url = e.get("url")
    title_html = f'<a href="{esc(url)}">{title}</a>' if url else title

    parts = [f'<span class="entry-title">{title_html}</span>', authors_phrase(e.get("authors"))]

    detail, badge = split_badge(e.get("detail"))
    meta = []
    if e.get("venue"):
        meta.append(emphasise(e["venue"]))
    if detail:
        meta.append(esc(detail))
    if e.get("lang") == "ko":
        meta.append("in Korean")

    tail = ""
    if meta:
        tail += f'<span class="entry-venue">{", ".join(meta)}</span>'
    if badge:
        sep = " " if tail else ""
        tail += f'{sep}<span class="badge-soft">{esc(badge)}</span>'
    if tail:
        parts.append(f'<span class="entry-meta">{tail}</span>')

    extras = e.get("extras") or []
    if extras:
        links = "".join(
            f'<a href="{esc(x["href"])}">{esc(x["label"])}</a>' for x in extras
        )
        parts.append(f'<span class="extras">{links}</span>')

    return "<li>" + "".join(parts) + "</li>"


def build_research():
    pubs = load("publications.yml")
    out = [
        "---",
        'title: "Research"',
        "---",
        "",
        BANNER.format(src="publications.yml"),
        "",
        "## Research Interest",
        "",
        "- **Primary:** Empirical Macro, Forecasting, Time-series",
        "- **Secondary:** Macroeconometrics, Data Mining",
        "",
    ]
    total = 0
    for key, heading in SECTIONS:
        items = pubs.get(key) or []
        if not items:
            continue
        total += len(items)
        out += [f"## {heading}", "", '<ol class="entries">']
        out += [render_entry(e) for e in items]
        out += ["</ol>", ""]

    grants = load("grants.yml") or []
    if grants:
        total += len(grants)
        out += ["## Research Grants", "", '<ol class="entries entries-grant">']
        for g in sorted(grants, key=lambda x: x["year"], reverse=True):
            meta = [esc(g["funder"]), esc(g["role"])]
            if g.get("amount"):
                meta.append(esc(g["amount"]))
            out.append(
                "<li>"
                f'<span class="grant-year">{esc(g["year"])}</span>'
                f'<span class="entry-title">{esc(g["title"])}</span>'
                f'<span class="entry-meta"><span class="proj-client">'
                f'{" · ".join(meta)}</span></span>'
                "</li>"
            )
        out += ["</ol>", ""]

    write("research.qmd", out)
    return total


ROLE_EN = {"책임": "Principal investigator", "공동": "Co-investigator"}


def project_list(projects, lang):
    """Render one language's list. `entries-proj` puts the period in its own
    grid column so that a title wrapping to a second line stays aligned with
    the first, instead of running back under the period."""
    rows = ['<ol class="entries entries-proj">']
    for p in projects:
        title = p["title_en"] if lang == "en" else p["title"]
        client = p["client_en"] if lang == "en" else p["client"]
        role = ROLE_EN[p["role"]] if lang == "en" else p["role"]
        rows.append(
            "<li>"
            f'<span class="proj-period">{esc(p["period"])}</span>'
            f'<span class="entry-title">{esc(title)}</span>'
            f'<span class="entry-meta"><span class="proj-client">'
            f'{esc(client)} · {esc(role)}</span></span>'
            "</li>"
        )
    rows.append("</ol>")
    return rows


def build_projects():
    projects = sorted(load("projects.yml"), key=lambda p: p["start"], reverse=True)
    out = [
        "---",
        'title: "Projects"',
        "---",
        "",
        BANNER.format(src="projects.yml"),
        "",
        "Commissioned research projects. 연구용역 목록입니다.",
        "",
        "::: {.panel-tabset}",
        "",
        "## 한국어",
        "",
    ]
    out += project_list(projects, "ko")
    out += ["", "## English", ""]
    out += project_list(projects, "en")
    out += ["", ":::", ""]
    write("projects.qmd", out)
    return len(projects)


def write(name, lines):
    with io.open(os.path.join(ROOT, name), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines).rstrip() + "\n")
    print(f"  wrote {name}")


if __name__ == "__main__":
    print("build.py: generating pages from data/")
    n_pubs = build_research()
    n_proj = build_projects()
    print(f"  research.qmd : {n_pubs} entries")
    print(f"  projects.qmd : {n_proj} entries")
    sys.exit(0)
