<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-10-02">
<meta name="description" content="About 80 percent of each change in Korea’s cap on refiners’ supply prices reached pump prices within two weeks, faster where stations are more numerous and at self-service and highway stations, and cuts travelled faster than increases. The cap stayed below the supply price implied by international product prices throughout, and the gap was absorbed by refiners and the fuel-tax cut, not by station margins.">

<title>Two Weeks to the Pump – Hyun Hak Kim</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-0b873dab1a9bb082c1df6b2c2700682a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-d7d8c43c9bbf52025258093b17e489d4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-0b873dab1a9bb082c1df6b2c2700682a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,400;8..60,600;8..60,700&amp;display=swap">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Two Weeks to the Pump – Hyun Hak Kim">
<meta property="og:description" content="About 80 percent of each change in Korea’s cap on refiners’ supply prices reached pump prices within two weeks, faster where stations are more numerous and at self-service and highway stations, and cuts travelled faster than increases. The cap stayed below the supply price implied by international product prices throughout, and the gap was absorbed by refiners and the fuel-tax cut, not by station margins.">
<meta property="og:image" content="https://khdouble.github.io/posts/2026-10-fuel-price-cap-en/figures/figure5_cap_binding.png">
<meta property="og:site_name" content="Hyun Hak Kim">
<meta property="og:image:height" content="795">
<meta property="og:image:width" content="2614">
<meta property="og:image:alt" content="Refiner weekly supply prices, the cap, and the estimated supply price without the cap, for gasoline and diesel">
</head>

<body class="nav-sidebar docked article quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      Hyun Hak Kim
      </li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Hyun Hak Kim</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="../../files/cv-hyunhak-kim.pdf" title="Curriculum Vitae" class="quarto-navigation-tool px-1" aria-label="Curriculum Vitae"><i class="bi bi-file-earmark-text"></i></a>
    <a href="mailto:hyunhak.kim@kookmin.ac.kr" title="Email" class="quarto-navigation-tool px-1" aria-label="Email"><i class="bi bi-envelope"></i></a>
    <a href="https://www.linkedin.com/in/khdouble/" title="LinkedIn" class="quarto-navigation-tool px-1" aria-label="LinkedIn"><i class="bi bi-linkedin"></i></a>
    <a href="https://github.com/khdouble" title="GitHub" class="quarto-navigation-tool px-1" aria-label="GitHub"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Research</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../blog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Blog</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../links.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Links</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#a-cap-on-the-wholesale-price-changed-on-announced-dates" id="toc-a-cap-on-the-wholesale-price-changed-on-announced-dates" class="nav-link active" data-scroll-target="#a-cap-on-the-wholesale-price-changed-on-announced-dates">A cap on the wholesale price, changed on announced dates</a></li>
  <li><a href="#data-and-measures" id="toc-data-and-measures" class="nav-link" data-scroll-target="#data-and-measures">1. Data and measures</a></li>
  <li><a href="#stations-moved-on-the-day-the-cap-changed" id="toc-stations-moved-on-the-day-the-cap-changed" class="nav-link" data-scroll-target="#stations-moved-on-the-day-the-cap-changed">2. Stations moved on the day the cap changed</a></li>
  <li><a href="#about-80-percent-in-two-weeks" id="toc-about-80-percent-in-two-weeks" class="nav-link" data-scroll-target="#about-80-percent-in-two-weeks">3. About 80 percent in two weeks</a></li>
  <li><a href="#faster-where-there-are-more-stations-nearby" id="toc-faster-where-there-are-more-stations-nearby" class="nav-link" data-scroll-target="#faster-where-there-are-more-stations-nearby">4. Faster where there are more stations nearby</a></li>
  <li><a href="#cuts-travelled-faster-than-increases" id="toc-cuts-travelled-faster-than-increases" class="nav-link" data-scroll-target="#cuts-travelled-faster-than-increases">5. Cuts travelled faster than increases</a></li>
  <li><a href="#no-sign-that-same-brand-neighbours-timed-their-changes-together" id="toc-no-sign-that-same-brand-neighbours-timed-their-changes-together" class="nav-link" data-scroll-target="#no-sign-that-same-brand-neighbours-timed-their-changes-together">6. No sign that same-brand neighbours timed their changes together</a></li>
  <li><a href="#the-cap-sat-below-cost-every-week-and-refiners-and-the-tax-cut-absorbed-the-gap" id="toc-the-cap-sat-below-cost-every-week-and-refiners-and-the-tax-cut-absorbed-the-gap" class="nav-link" data-scroll-target="#the-cap-sat-below-cost-every-week-and-refiners-and-the-tax-cut-absorbed-the-gap">7. The cap sat below cost every week, and refiners and the tax cut absorbed the gap</a></li>
  <li><a href="#compared-with-europe" id="toc-compared-with-europe" class="nav-link" data-scroll-target="#compared-with-europe">8. Compared with Europe?</a></li>
  <li><a href="#what-is-established-and-what-is-not" id="toc-what-is-established-and-what-is-not" class="nav-link" data-scroll-target="#what-is-established-and-what-is-not">9. What is established, and what is not</a></li>
  <li><a href="#implications" id="toc-implications" class="nav-link" data-scroll-target="#implications">10. Implications</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Two Weeks to the Pump</h1>
<p class="subtitle lead">How Korea’s 2026 cap on refiners’ supply prices reached retail fuel prices, where it reached them faster, and who absorbed the gap between the cap and cost</p>
  <div class="quarto-categories">
    <div class="quarto-category">English</div>
    <div class="quarto-category">Energy</div>
    <div class="quarto-category">Competition Policy</div>
  </div>
  </div>

<div>
  <div class="description">
    About 80 percent of each change in Korea’s cap on refiners’ supply prices reached pump prices within two weeks, faster where stations are more numerous and at self-service and highway stations, and cuts travelled faster than increases. The cap stayed below the supply price implied by international product prices throughout, and the gap was absorbed by refiners and the fuel-tax cut, not by station margins.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 2, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>한국어판</strong> — <a href="../2026-10-fuel-price-cap-ko/">기름값 상한, 주유소까지 2주 걸렸다</a></p>
<p>Retail prices are the daily prices of 10,744 Korean gas stations of the four refiners’ brands and the Altteul discount brand, 29 December 2024 to 30 September 2026, published by Opinet, the price portal of the Korea National Oil Corporation. Refiners’ weekly supply prices also come from Opinet, international product prices are Singapore spot quotes, exchange rates come from the Bank of Korea’s ECOS, and regional shipments from the Korea National Oil Corporation’s Petronet. Station locations come from geocoding addresses with the VWorld geocoder. Hypotheses and methods were written down and frozen before the relevant results were examined.</p>
</div>
</div>
</div>
<section id="a-cap-on-the-wholesale-price-changed-on-announced-dates" class="level2">
<h2 class="anchored" data-anchor-id="a-cap-on-the-wholesale-price-changed-on-announced-dates">A cap on the wholesale price, changed on announced dates</h2>
<p>When international fuel prices spiked during the 2026 Middle East war, the Korean government put a maximum price on what refiners charge gas stations, starting 13 March 2026. The first cap was 1,724 won per liter for gasoline and 1,713 won for diesel. It rose by 210 won on 27 March, the same day the fuel-tax cut widened from 7 to 15 percent for gasoline and from 10 to 25 percent for diesel. The cap was then frozen four times, cut by 150 won on 27 June, and frozen three more times; from the sixth decision the review interval lengthened from two to four weeks.</p>
<p>Two features make the episode informative. The cap sits on the wholesale price, not on what drivers pay. And each change is announced with its date and size, so for a station it is a cost shock of known timing and magnitude. Pass-through of temporary fuel-tax cuts has been studied extensively for Germany and other European countries in 2022, and Hungary’s 2021–22 retail cap has been analysed, but I have not found station-level daily evidence on a repeatedly revised cap on refiners’ prices. This note asks four questions: how fast cap changes reach pump prices and whether speed differs with the number of nearby stations; whether increases and cuts travel at the same speed; whether neighbouring stations of the same brand time their changes together; and where the cap sat relative to cost, and who absorbed the gap.</p>
<section id="headline-figures" class="level3">
<h3 class="anchored" data-anchor-id="headline-figures">Headline figures</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Stations, daily</td>
<td style="text-align: right;">10,744, 29 Dec 2024 – 30 Sep 2026</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stations changing price on 13 March (refiner brands)</td>
<td style="text-align: right;">54–63%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Largest rise in that share on the seven no-change dates</td>
<td style="text-align: right;">3.6 points</td>
</tr>
<tr class="even">
<td style="text-align: left;">Share passed through after 1 / 2 / 3 weeks, 27 March increase</td>
<td style="text-align: right;">0.54 / 0.81 / 0.86</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Share passed through after 1 / 2 / 3 weeks, 27 June cut</td>
<td style="text-align: right;">0.67 / 0.83 / 0.88</td>
</tr>
<tr class="even">
<td style="text-align: left;">Increase minus cut after 1 week, same 9,933 stations</td>
<td style="text-align: right;">−0.133 (0.010)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Coefficient on log stations in the city, cut, day 7</td>
<td style="text-align: right;">0.054 (0.010)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cap minus estimated uncapped supply price, gasoline / diesel</td>
<td style="text-align: right;">−4 to −208 / −4 to −1,042 won by week</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Station margin on gasoline, 2025 / cap period</td>
<td style="text-align: right;">71 / 77–87 won per liter</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="data-and-measures" class="level2">
<h2 class="anchored" data-anchor-id="data-and-measures">1. Data and measures</h2>
<p>Station prices are Opinet’s historical daily prices for regular gasoline and automotive diesel. The sample covers stations of SK Energy, GS Caltex, HD Hyundai Oilbank and S-OIL and the Altteul discount brand, including its highway and agricultural-cooperative variants; private-label stations are dropped. Each station’s city (<em>si-gun</em>) is fixed at its modal label before 1 July 2026, when the merger of Gwangju and South Jeolla and a reorganisation of Incheon’s districts changed the labels. A price that moves by 300 won or more and returns the next day is treated as a recording error (147 gasoline and 238 diesel observations).</p>
<p>The cumulative pass-through of station <span class="math inline">\(i\)</span>, <span class="math inline">\(r\)</span> days after a cap change on day <span class="math inline">\(\tau\)</span>, is</p>
<p><span class="math display">\[PT_{i,r}=\frac{p_{i,\tau+r}-p_{i,\tau-1}}{\Delta c},\]</span></p>
<p>with <span class="math inline">\(\Delta c=210\)</span> for the March increase and <span class="math inline">\(-150\)</span> for the June cut. The 13 March start is used only for timing, because weekly supply prices cannot measure the size of a change introduced mid-week. Each event sample keeps stations observed on at least 80 percent of days from a week before to three weeks after, observed the day before, and not changing brand. Market structure enters as</p>
<p><span class="math display">\[PT_{i,r}=\beta_1\log N_{m(i)}+\beta_2\,\text{Self}_i+\beta_3\,\text{Highway}_i+\alpha_{b(i),s(i)}+u_i,\]</span></p>
<p>where <span class="math inline">\(N_m\)</span> is the number of stations in city <span class="math inline">\(m\)</span> in February 2026 and <span class="math inline">\(\alpha_{b,s}\)</span> is a brand-by-province effect, with standard errors clustered by city. The seven dates on which the cap was announced but left unchanged serve as placebos.</p>
</section>
<section id="stations-moved-on-the-day-the-cap-changed" class="level2">
<h2 class="anchored" data-anchor-id="stations-moved-on-the-day-the-cap-changed">2. Stations moved on the day the cap changed</h2>
<p>On a normal day in 2026, 3–6 percent of stations changed their price. On 13 March, when the cap took effect, 54–63 percent of refiner-brand stations and 89 percent of Altteul stations did. About 40 percent changed on the day after the March increase and on the Monday after the Saturday cut in June. On the seven no-change dates the share rose by at most 3.6 percentage points. The busiest day of the year was earlier, in early March (83 percent of refiner-brand stations), during the surge in international prices before the cap; the spikes at each cap change are separate from it.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure1_change_share.png" class="img-fluid figure-img"></p>
<figcaption>Figure 1. Share of stations changing their gasoline price each day. Solid lines mark cap changes with a price change; dotted lines mark decisions that left the cap unchanged. The early-March spike precedes the cap and coincides with the surge in international prices.</figcaption>
</figure>
</div>
</section>
<section id="about-80-percent-in-two-weeks" class="level2">
<h2 class="anchored" data-anchor-id="about-80-percent-in-two-weeks">3. About 80 percent in two weeks</h2>
<p>The first price change came quickly, with a median of zero to two days at refiner-brand stations. Completing the adjustment took two to three weeks.</p>
<table class="caption-top table">
<caption>Mean cumulative pass-through, gasoline. Diesel is similar: 0.80 (increase) and 0.86 (cut) after two weeks.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Event</th>
<th style="text-align: right;">Cap change</th>
<th style="text-align: right;">1 week</th>
<th style="text-align: right;">2 weeks</th>
<th style="text-align: right;">3 weeks</th>
<th style="text-align: right;">Stations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">27 March increase</td>
<td style="text-align: right;">+210 won</td>
<td style="text-align: right;">0.536</td>
<td style="text-align: right;">0.808</td>
<td style="text-align: right;">0.861</td>
<td style="text-align: right;">10,151</td>
</tr>
<tr class="even">
<td style="text-align: left;">27 June cut</td>
<td style="text-align: right;">−150 won</td>
<td style="text-align: right;">0.670</td>
<td style="text-align: right;">0.830</td>
<td style="text-align: right;">0.879</td>
<td style="text-align: right;">10,038</td>
</tr>
</tbody>
</table>
<p>Altteul stations followed their own path. After the increase they barely moved for two days, jumped on the third, and ended above the refiner brands at 0.89 after three weeks; after the cut they lagged slightly. This fits a supply price set weekly through the Korea National Oil Corporation’s group purchase.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure2_passthrough_paths.png" class="img-fluid figure-img"></p>
<figcaption>Figure 2. Cumulative pass-through after each cap change. Panels (a) and (b) show mean pass-through by brand group; the dashed line marks full pass-through. Panel (c) shows the within-station difference, increase minus cut, for the 9,933 stations in both samples, with 95 percent intervals clustered by city.</figcaption>
</figure>
</div>
</section>
<section id="faster-where-there-are-more-stations-nearby" class="level2">
<h2 class="anchored" data-anchor-id="faster-where-there-are-more-stations-nearby">4. Faster where there are more stations nearby</h2>
<p>Within a brand and province, the June cut reached pump prices faster in cities with more stations. One week after the cut, a city with twice as many stations had prices about 5.6 won lower (coefficient 0.054). Self-service stations were 0.127 ahead of full-service stations (about 19 won) and highway stations 0.154 ahead (about 23 won).</p>
<table class="caption-top table">
<caption>Coefficient on log stations in the city. Brand-by-province effects (by event when pooled), self-service and highway indicators included; city-clustered standard errors over 229 cities. On the placebo dates the same coefficient on the one-week price change is −0.34 won for gasoline, less than one-twentieth of the effect on event dates.</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Day 3</th>
<th style="text-align: right;">Day 7</th>
<th style="text-align: right;">Day 14</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">27 June cut</td>
<td style="text-align: right;">0.062 (0.010)</td>
<td style="text-align: right;">0.054 (0.010)</td>
<td style="text-align: right;">0.035 (0.008)</td>
</tr>
<tr class="even">
<td style="text-align: left;">27 March increase</td>
<td style="text-align: right;">0.011 (0.010)</td>
<td style="text-align: right;">−0.006 (0.009)</td>
<td style="text-align: right;">0.023 (0.006)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Three events pooled, gasoline</td>
<td style="text-align: right;">0.069 (0.016)</td>
<td style="text-align: right;">0.053 (0.016)</td>
<td style="text-align: right;">0.049 (0.014)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Three events pooled, diesel</td>
<td style="text-align: right;">0.051 (0.011)</td>
<td style="text-align: right;">0.039 (0.010)</td>
<td style="text-align: right;">0.038 (0.008)</td>
</tr>
</tbody>
</table>
<p>For the increase, city size made no difference in the first week and mattered only in the second. Cities with more stations passed the cut through first and caught up on the increase later. Self-service and highway stations were faster in both directions; highway stations were 0.381 ahead one week after the increase.</p>
<p>A city-level comparison can mix in other urban–rural differences, so I also compared stations of the same brand within the same city by the number of rival stations within 1 km. One week after the June cut, stations with no rival within 1 km had passed through 57 percent of it, those with one or two 68 percent, three to five 74 percent and six or more 78 percent. Controlling for how often each station changed its price before the cap shrinks this gradient by about a sixth but leaves it in place. It is an association, not proof that competition caused the faster response: the number of nearby rivals also goes with turnover and other station traits. By the third week the gap had largely closed.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure3_market_structure.png" class="img-fluid figure-img"></p>
<figcaption>Figure 3. Market structure and speed of pass-through. (a) Coefficient on log stations in the city; (b) self-service and highway coefficients at day 7, with 95 percent city-clustered intervals; (c) mean pass-through at day 7 by tercile of city station count.</figcaption>
</figure>
</div>
</section>
<section id="cuts-travelled-faster-than-increases" class="level2">
<h2 class="anchored" data-anchor-id="cuts-travelled-faster-than-increases">5. Cuts travelled faster than increases</h2>
<p>Fuel prices are said to rise like rockets and fall like feathers (Borenstein, Cameron and Gilbert, 1997). Here the reverse held. Among the 9,933 stations in both samples, pass-through after one week was 0.133 lower for the increase than for the cut (standard error 0.010), and 0.176 lower for diesel. After two weeks the gap had shrunk to 0.022. All four refiner brands moved the same way; Altteul showed no gap.</p>
<p>The result needs care. There is one increase and one cut. The increase coincided with a larger fuel-tax cut that softened the change drivers saw, and fuel prices were under close government and press scrutiny. The asymmetry was also noticed after part of the data had been seen, so it is not a pre-registered result. I will re-test it on the next cap change with a method fixed in advance.</p>
</section>
<section id="no-sign-that-same-brand-neighbours-timed-their-changes-together" class="level2">
<h2 class="anchored" data-anchor-id="no-sign-that-same-brand-neighbours-timed-their-changes-together">6. No sign that same-brand neighbours timed their changes together</h2>
<p>Same-brand pairs in the same city changed price on the same day 0.2–0.5 percentage points more often than different-brand pairs. That gap is exactly what one expects when brands differ in how often they change prices. Two stations moving independently change together with probability equal to the product of their probabilities, and the cross-brand product <span class="math inline">\(p_b p_{b'}\)</span> is smaller than the same-brand average <span class="math inline">\((p_b^2+p_{b'}^2)/2\)</span>. The standard regression — same-day change on a same-brand indicator with city-by-day and brand-by-day effects — inherits this bias. I therefore measure excess co-movement: the observed same-day change minus the product of each station’s brand-province-day change rate, leaving the pair out. This correction was made before estimation.</p>
<p>On event dates, excess co-movement for same-brand pairs was −0.89 per 1,000 pair-days (standard error 0.64), not positive. The standard regression gave +2.80 (0.63) on event dates and +0.94 (0.11) on dates when the cap did not change — the bias, not coordination. The exception was Altteul pairs, with excess co-movement of 8.6 (2.8), consistent with their weekly group-purchase pricing.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure4_same_brand_timing.png" class="img-fluid figure-img"></p>
<figcaption>Figure 4. Excess same-day price changes of same-brand pairs, gasoline, eight days after each date. (a) The standard additive regression; (b) excess over the independent benchmark. Hollow markers are pooled estimates; intervals are 95 percent, clustered by city.</figcaption>
</figure>
</div>
</section>
<section id="the-cap-sat-below-cost-every-week-and-refiners-and-the-tax-cut-absorbed-the-gap" class="level2">
<h2 class="anchored" data-anchor-id="the-cap-sat-below-cost-every-week-and-refiners-and-the-tax-cut-absorbed-the-gap">7. The cap sat below cost every week, and refiners and the tax cut absorbed the gap</h2>
<p>Throughout the cap period the refiners’ supply prices sat 2–6 won below the cap. On its own that has two readings. The cap may have been below cost, so everyone charged up to it. Or costs may have fallen below the cap while the cap served as a reference point that kept prices up — the idea that a price ceiling can become a focal point for tacit collusion (Knittel and Stango, 2003; Zhang et al., 2020).</p>
<p>To tell them apart I estimated a pre-cap pricing rule: pre-tax supply prices on the won value of Singapore product prices and two weekly lags, January 2025 to February 2026 (60 weeks; adjusted <span class="math inline">\(R^2\)</span> 0.919 for gasoline and 0.946 for diesel; residual standard deviation 10.6 and 11.9 won after tax). Applied to the cap period with the fuel-tax schedule implied by Opinet’s pre-tax and after-tax supply prices, the rule gives the price refiners would have charged without the cap. In none of the 22 cap-period weeks, excluding transition weeks, did the cap exceed this estimate, for either fuel; the same holds with a shorter estimation window, a fixed-markup rule and a four-week lag rule. The cap was 4–208 won below the estimate for gasoline and 4–1,042 won below it for diesel, the largest gap in early April; the two or three closest weeks, in mid-June and early July, were within the rule’s error, so the test cannot say whether the cap bound then; the remaining 19 weeks for gasoline and 20 for diesel were far outside it.</p>
<p>Crude oil prices alone suggest the cap was above cost in July and August. But in 2026 gasoline and diesel prices rose far more than crude, and on a product basis the cap never was. All four refiners sitting at the cap is therefore best read as the cap holding prices below cost. It also means that parallel pricing during the cap carries no information about collusion.</p>
<p>The average station margin, national mean retail price minus refiners’ mean supply price, barely changed. Individual stations’ purchase prices are not published, so this describes stations as a group, not any one station. What drivers saved came from refiners’ supply prices and from the public budget through the tax cut.</p>
<p>Weighting by Petronet’s monthly shipments, the gap between the estimated uncapped supply price and the cap comes to about 3.0 trillion won for April–August, against about 2.0 trillion won of revenue forgone through the fuel-tax cut over the same months. The first figure values refiners’ sales at international product prices: it is an opportunity cost, not an accounting loss, and not the compensation the government will set through its settlement committee. It also relies on the pre-cap pricing rule holding at the extreme prices of 2026.</p>
<table class="caption-top table">
<caption>Station margin, won per liter: weekly mean retail price of refiner-brand stations minus refiners’ weekly mean supply price. Transition weeks are excluded because weekly averages straddle the change date.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Period</th>
<th style="text-align: right;">Gasoline</th>
<th style="text-align: right;">Diesel</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2025</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">81</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jan–Feb 2026</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">89</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Apr–Jun 2026 (cap 1,934 won)</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">82</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jul–Sep 2026 (cap 1,784 won)</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">83</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure5_cap_binding.png" class="img-fluid figure-img"></p>
<figcaption>Figure 5. Supply price, cap and estimated uncapped supply price. In (a) and (b) the solid line is the refiners’ weekly mean supply price after tax, the step line the cap, and the dashed line the price implied by the pre-cap rule; shading marks the cap period. (c) Station margins; the spikes at transition weeks reflect weekly averages that straddle the change date.</figcaption>
</figure>
</div>
</section>
<section id="compared-with-europe" class="level2">
<h2 class="anchored" data-anchor-id="compared-with-europe">8. Compared with Europe?</h2>
<p>Europe took a different route in 2026. At least 15 of the 27 EU member states cut excise duty or VAT on diesel between March and September; Greece, Romania and Czechia capped distribution or retail margins. I found no country that capped refiners’ prices.</p>
<p>Did Korea’s cap keep prices lower than Europe’s? I compared Korea’s pre-tax retail prices with a weighted combination of European countries that tracked Korea closely over the two years before the cap (a synthetic control). In the 25 weeks after the cap, Korea’s pre-tax diesel price was about 260 won per liter below this benchmark, and gasoline about 120 won below.</p>
<p>That gap cannot be read as the effect of the cap. Eight of the 13 comparison countries chosen in advance turned out to have intervened themselves, with margin caps, tax cuts or an export ban, and the pre-registered test did not pass. Keeping only countries without such measures leaves four to six, too few to tell the gap from chance. I therefore left the comparison out of the paper. Korea’s pre-tax prices rose less than Europe’s; how much of that was the cap, these data cannot say.</p>
</section>
<section id="what-is-established-and-what-is-not" class="level2">
<h2 class="anchored" data-anchor-id="what-is-established-and-what-is-not">9. What is established, and what is not</h2>
<p><strong>Established.</strong> Cap changes concentrated price changes on the change date and reached pump prices by about 80 percent within two weeks and 85–90 percent within three. Cuts reached prices faster in cities with more stations and at self-service and highway stations, with no such differences on placebo dates. The cap sat below the estimated cost-based price every week, beyond the rule’s error in 19 of 22 weeks for gasoline and 20 for diesel, and the average station margin did not change materially.</p>
<p><strong>Ruled out.</strong> That same-brand neighbours time their changes together: the positive coefficient of the standard regression appears on placebo dates too. That the cap became a floor holding supply prices up after costs fell below it: on a product-price basis, costs never did. That the cap compressed price dispersion within cities: dispersion fell by 40–60 percent, but within the range implied by the pre-cap relation between price levels and dispersion (Lewis and Marvel, 2011).</p>
<p><strong>Open.</strong> Whether cuts travelling faster than increases is a general feature of this kind of cap, given one event of each kind and an increase that coincided with a tax cut. The pass-through level at the 13 March start, which weekly supply prices cannot pin down. How far the cap held prices below their level without it, which the European comparison in section 8 could not settle. The refiners’ burden beyond the opportunity-cost estimate above. Supply responses such as exports or inventory draws while the cap sat far below cost. And the July 2026 indictment of the four refiners over how they set supply prices, which these data cannot speak to.</p>
</section>
<section id="implications" class="level2">
<h2 class="anchored" data-anchor-id="implications">10. Implications</h2>
<p>A wholesale cap reaches pump prices quickly but not at once: more than half in the first week and most within three. Judging a cap change by pump prices a few days later understates its effect. Speed differs with the number of nearby stations, so drivers in areas with few stations see a cut later; monitoring right after a cut is best aimed at stations with no rival within 1 km. When a cap sits far below cost, the supply side absorbs the gap — here refiners (about 3 trillion won, an opportunity-cost estimate) and the public budget (about 2 trillion won through the tax cut) — and the longer that lasts, the more sales and export data should be watched alongside prices. And while a cap sits at or below cost, firms charge the same price near it whether or not they compete, so parallel pricing during the cap is weak evidence for a competition authority.</p>
<section id="data-and-code" class="level3">
<h3 class="anchored" data-anchor-id="data-and-code">Data and code</h3>
<p>All data are public. Station prices, refiner supply prices and international product prices come from <a href="https://www.opinet.co.kr">Opinet</a>; exchange rates from the <a href="https://ecos.bok.or.kr">Bank of Korea ECOS</a>; shipments from <a href="https://www.petronet.co.kr">Petronet</a>; station coordinates from the <a href="https://www.vworld.kr">VWorld</a> geocoder. Cap decisions are compiled from government announcements and press reports; fuel-tax rates are read off the gap between Opinet’s after-tax and pre-tax supply prices. The pre-registered analysis plans, the deviation log and the estimation code are available on request at <a href="mailto:hyunhak.kim@kookmin.ac.kr">hyunhak.kim@kookmin.ac.kr</a>.</p>
</section>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<p>Borenstein, S., Cameron, A. C. and Gilbert, R. (1997). Do gasoline prices respond asymmetrically to crude oil price changes? <em>Quarterly Journal of Economics</em>, 112(1), 305–339.</p>
<p>Knittel, C. R. and Stango, V. (2003). Price ceilings as focal points for tacit collusion: evidence from credit cards. <em>American Economic Review</em>, 93(5), 1703–1729.</p>
<p>Lewis, M. S. (2011). Asymmetric price adjustment and consumer search: an examination of the retail gasoline market. <em>Journal of Economics &amp; Management Strategy</em>, 20(2), 409–449.</p>
<p>Lewis, M. S. and Marvel, H. P. (2011). When do consumers search? <em>Journal of Industrial Economics</em>, 59(3), 457–483.</p>
<p>Zhang, X.-B., Fei, Y., Zheng, Y. and Zhang, L. (2020). Price ceilings as focal points to reach price uniformity: evidence from a Chinese gasoline market. <em>Energy Economics</em>, 92.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/khdouble\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© Hyun Hak Kim · Department of Economics, Kookmin University</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>