<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-20">
<meta name="description" content="Korean manufacturers run 1,399 geocoded plants abroad and draw a third of their embodied value added from foreign suppliers. This note sets out how far a severe flood, drought or heatwave at those sites travels into a firm’s accounts — and where country-average exposure data go wrong.">

<title>Where Imported Climate Risk Stops – Hyun Hak Kim</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-0b873dab1a9bb082c1df6b2c2700682a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-d7d8c43c9bbf52025258093b17e489d4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-0b873dab1a9bb082c1df6b2c2700682a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,400;8..60,600;8..60,700&amp;display=swap">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Where Imported Climate Risk Stops – Hyun Hak Kim">
<meta property="og:description" content="Korean manufacturers run 1,399 geocoded plants abroad and draw a third of their embodied value added from foreign suppliers. This note sets out how far a severe flood, drought or heatwave at those sites travels into a firm’s accounts — and where country-average exposure data go wrong.">
<meta property="og:image" content="https://khdouble.github.io/posts/2026-09-imported-climate-risk-en/figures/figure1_sites_map.png">
<meta property="og:site_name" content="Hyun Hak Kim">
<meta property="og:image:height" content="526">
<meta property="og:image:width" content="1183">
<meta property="og:image:alt" content="World map of the overseas plants and sales offices of Korean listed manufacturers">
</head>

<body class="nav-sidebar docked article quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      Hyun Hak Kim
      </li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Hyun Hak Kim</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="../../files/cv-hyunhak-kim.pdf" title="Curriculum Vitae" class="quarto-navigation-tool px-1" aria-label="Curriculum Vitae"><i class="bi bi-file-earmark-text"></i></a>
    <a href="mailto:hyunhak.kim@kookmin.ac.kr" title="Email" class="quarto-navigation-tool px-1" aria-label="Email"><i class="bi bi-envelope"></i></a>
    <a href="https://www.linkedin.com/in/khdouble/" title="LinkedIn" class="quarto-navigation-tool px-1" aria-label="LinkedIn"><i class="bi bi-linkedin"></i></a>
    <a href="https://github.com/khdouble" title="GitHub" class="quarto-navigation-tool px-1" aria-label="GitHub"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Research</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../blog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Blog</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../links.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Links</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#how-far-does-a-climate-shock-abroad-travel-into-a-korean-manufacturers-accounts" id="toc-how-far-does-a-climate-shock-abroad-travel-into-a-korean-manufacturers-accounts" class="nav-link active" data-scroll-target="#how-far-does-a-climate-shock-abroad-travel-into-a-korean-manufacturers-accounts">How far does a climate shock abroad travel into a Korean manufacturer’s accounts?</a></li>
  <li><a href="#two-channels-and-only-one-can-be-measured-where-the-shock-lands" id="toc-two-channels-and-only-one-can-be-measured-where-the-shock-lands" class="nav-link" data-scroll-target="#two-channels-and-only-one-can-be-measured-where-the-shock-lands">1. Two channels, and only one can be measured where the shock lands</a></li>
  <li><a href="#national-averages-describe-territory-not-production" id="toc-national-averages-describe-territory-not-production" class="nav-link" data-scroll-target="#national-averages-describe-territory-not-production">2. National averages describe territory, not production</a></li>
  <li><a href="#damage-reaches-the-consolidated-balance-sheet-and-stops-there" id="toc-damage-reaches-the-consolidated-balance-sheet-and-stops-there" class="nav-link" data-scroll-target="#damage-reaches-the-consolidated-balance-sheet-and-stops-there">3. Damage reaches the consolidated balance sheet and stops there</a></li>
  <li><a href="#three-placebos-separate-three-confounds-that-usually-travel-together" id="toc-three-placebos-separate-three-confounds-that-usually-travel-together" class="nav-link" data-scroll-target="#three-placebos-separate-three-confounds-that-usually-travel-together">4. Three placebos separate three confounds that usually travel together</a></li>
  <li><a href="#through-the-trade-channel-the-shock-arrives-as-a-fifth-of-a-percent" id="toc-through-the-trade-channel-the-shock-arrives-as-a-fifth-of-a-percent" class="nav-link" data-scroll-target="#through-the-trade-channel-the-shock-arrives-as-a-fifth-of-a-percent">5. Through the trade channel the shock arrives as a fifth of a percent</a></li>
  <li><a href="#most-hazards-are-precise-nulls-and-flood-is-the-exception" id="toc-most-hazards-are-precise-nulls-and-flood-is-the-exception" class="nav-link" data-scroll-target="#most-hazards-are-precise-nulls-and-flood-is-the-exception">6. Most hazards are precise nulls, and flood is the exception</a></li>
  <li><a href="#extreme-heat-is-where-the-evidence-divides" id="toc-extreme-heat-is-where-the-evidence-divides" class="nav-link" data-scroll-target="#extreme-heat-is-where-the-evidence-divides">7. Extreme heat is where the evidence divides</a></li>
  <li><a href="#the-boundary-of-what-the-current-evidence-supports" id="toc-the-boundary-of-what-the-current-evidence-supports" class="nav-link" data-scroll-target="#the-boundary-of-what-the-current-evidence-supports">8. The boundary of what the current evidence supports</a></li>
  <li><a href="#finer-resolution-not-a-longer-sample" id="toc-finer-resolution-not-a-longer-sample" class="nav-link" data-scroll-target="#finer-resolution-not-a-longer-sample">9. Finer resolution, not a longer sample</a></li>
  <li><a href="#working-paper" id="toc-working-paper" class="nav-link" data-scroll-target="#working-paper">Working paper</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Where Imported Climate Risk Stops</h1>
<p class="subtitle lead">How far a flood, drought or heatwave abroad travels into a Korean manufacturer’s accounts, what each null result rules out, and why national-average exposure data misstate what plants actually face</p>
  <div class="quarto-categories">
    <div class="quarto-category">English</div>
    <div class="quarto-category">Climate Risk</div>
    <div class="quarto-category">Global Value Chains</div>
  </div>
  </div>

<div>
  <div class="description">
    Korean manufacturers run 1,399 geocoded plants abroad and draw a third of their embodied value added from foreign suppliers. This note sets out how far a severe flood, drought or heatwave at those sites travels into a firm’s accounts — and where country-average exposure data go wrong.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 20, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>한국어판</strong> — <a href="../2026-09-imported-climate-risk-ko/">수입된 기후 리스크는 어디에서 멈추는가</a></p>
<p>Plant and sales-office coordinates come from the subsidiary tables of listed manufacturers’ annual reports — the 2024 filings, with 2022 addresses for plants that had left by then — and daily ERA5 and ERA5-Land weather is evaluated at each site over 2015–2024. The establishment panel is the Mining and Manufacturing Survey, 2002–2024, in 21 usable survey years.</p>
</div>
</div>
</div>
<section id="how-far-does-a-climate-shock-abroad-travel-into-a-korean-manufacturers-accounts" class="level2">
<h2 class="anchored" data-anchor-id="how-far-does-a-climate-shock-abroad-travel-into-a-korean-manufacturers-accounts">How far does a climate shock abroad travel into a Korean manufacturer’s accounts?</h2>
<p>Physical climate risk realised abroad reaches a manufacturing economy in two ways. Its firms buy intermediate inputs from countries that are getting hotter, drier and more frequently flooded, and they own plants in those same countries. Supervisors treat both as channels through which foreign disasters could impair domestic balance sheets, and both are now written into stress-testing frameworks.</p>
<p>Whether either channel operates at a magnitude that matters is an empirical question, and answering it requires measuring exposure where the shock actually lands and then following it outward, one step at a time. This study does that for Korean manufacturing over 2015–2024, using geocoded subsidiary disclosures, daily reanalysis weather, international input–output tables, customs records and establishment microdata. The clearest finding is that the shock reaches the accounts and stops there: a severe flood or drought at a firm’s principal overseas plant leaves consolidated asset growth about two percentage points below the parent’s separate-statement growth, and moves nothing else.</p>
<section id="headline-figures" class="level3">
<h3 class="anchored" data-anchor-id="headline-figures">Headline figures</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Overseas plants geocoded</td>
<td style="text-align: right;">1,399</td>
</tr>
<tr class="even">
<td style="text-align: left;">Consolidated asset growth after a severe flood, against separate</td>
<td style="text-align: right;">−2.15 points</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Profitability, capital expenditure and plant survival</td>
<td style="text-align: right;">No effect</td>
</tr>
<tr class="even">
<td style="text-align: left;">Capital expenditure, minimum detectable effect</td>
<td style="text-align: right;">0.18σ</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Input bill after a one-σ drought in an industry’s largest foreign origin</td>
<td style="text-align: right;">0.22%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Capital misallocation ruled out above</td>
<td style="text-align: right;">2% of dispersion</td>
</tr>
<tr class="odd">
<td style="text-align: left;">National averages overstate plant heat in Thailand by</td>
<td style="text-align: right;">3.6×</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="two-channels-and-only-one-can-be-measured-where-the-shock-lands" class="level2">
<h2 class="anchored" data-anchor-id="two-channels-and-only-one-can-be-measured-where-the-shock-lands">1. Two channels, and only one can be measured where the shock lands</h2>
<p>The trade channel is built from the Asian Development Bank’s multi-region input–output tables, which trace the value added embodied in Korean manufacturing output back to its country of origin. Foreign value added accounts for roughly a third of that output — 28 to 41 percent depending on the year, and 32.8 percent on the basis used in the dilution calculation below — and within the foreign component the largest single origin averages 23.5 percent across industries. Hazards in supplier economies are then weighted by each origin’s share of an industry’s foreign value added, lagged one year so the weights are fixed before the weather is known and renormalised to sum to one, so that the measure is the average risk of an industry’s foreign suppliers rather than a quantity that grows mechanically with how much the industry sources abroad. The resolution of this measure is the country-year, and that is its principal limitation.</p>
<p>For the ownership channel the resolution can be much finer, because Korean listed firms disclose the address of every consolidated subsidiary. From the annual reports of 2,240 listed manufacturers, subsidiaries whose stated business indicates production and whose address lies outside Korea yield 2,269 records with 1,859 distinct addresses.</p>
<p>Geocoding them is harder than it looks, and the difficulty is instructive about what disclosure data can support. Submitting the raw address strings to a gazetteer resolves 48 percent to city level or better, and the failures are not random: Korean filings render Chinese and Vietnamese place names in Korean transliteration, and industrial-park names that are locally canonical are absent from open gazetteers. A transliteration dictionary, sliding-window queries over address tokens, and a mapping of recurring park names to their host cities raise the rate to 92 percent on a 200-address development sample and 73 percent across all addresses.</p>
<p>Two classes of apparent successes mattered more than the failures, because they are silent. Ninety-six records carry romanised Korean addresses that the industry filter missed — the gazetteer resolves them correctly, but to Korea. Another 96 resolve to a country that contradicts a country name stated in the address itself: an address reading only “U.S.A” matching a street of that name in the Philippines, a Vietnamese address matching a building in Canada. Both classes were dropped.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure1_sites_map.png" class="img-fluid figure-img"></p>
<figcaption>Figure 1. Overseas sites of Korean listed manufacturers. The final panel is 1,399 manufacturing plants with city-level or better coordinates in 55 countries, belonging to 474 parent firms, alongside 1,844 sales offices of the same parents that serve as a placebo. Red marks the 271 plants that were a firm’s principal plant and were hit by a severe event between 2015 and 2024.</figcaption>
</figure>
</div>
<p>Daily ERA5-Land temperature and ERA5 precipitation and wind are then evaluated at every site. A validation against the Copernicus archive for the Chinese sites returns a correlation of 1.000 and a root-mean-square difference of 0.03°C. Tropical cyclone exposure is built separately, from the 2,775 IBTrACS storms that reached tropical-storm strength — 34 knots or more — between 1995 and 2025, a plant counting as exposed when a track point passes within a set radius. Its geography is itself a check on the coordinates: exposure rates of 79 percent in the Philippines and 78 percent in Japan, against 34 percent in China, 0.3 percent in near-equatorial Indonesia and zero in inland Europe, reproduce cyclone climatology without tuning.</p>
</section>
<section id="national-averages-describe-territory-not-production" class="level2">
<h2 class="anchored" data-anchor-id="national-averages-describe-territory-not-production">2. National averages describe territory, not production</h2>
<p>Having both a country-year and a plant-coordinate measure of the same hazards makes it possible to ask how much the country-year convention misstates what firms actually face. The two disagree systematically, and in opposite directions for heat and for rain.</p>
<table class="caption-top table">
<caption>Six of the twelve countries in the paper’s table, chosen to span the range. Annual values 2015–2024, averaged over years. “Plant” is the mean over Korean-owned manufacturing plants in the country, each evaluated at its coordinates. “National” is the country-year value published by the World Bank Climate Change Knowledge Portal from the same reanalysis. Rx5day is the maximum five-day precipitation total. Two omitted rows sharpen the point: Poland’s plants see 0.1 days above 35°C against a national 0.4, and Malaysia’s see none at all against a national 4.2.</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Country</th>
<th style="text-align: right;">Plants</th>
<th style="text-align: right;">Days &gt;35°C, plant</th>
<th style="text-align: right;">Days &gt;35°C, national</th>
<th style="text-align: right;">Rx5day (mm), plant</th>
<th style="text-align: right;">Rx5day (mm), national</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">China</td>
<td style="text-align: right;">434</td>
<td style="text-align: right;">5.8</td>
<td style="text-align: right;">7.0</td>
<td style="text-align: right;">145</td>
<td style="text-align: right;">59</td>
</tr>
<tr class="even">
<td style="text-align: left;">United States</td>
<td style="text-align: right;">228</td>
<td style="text-align: right;">9.9</td>
<td style="text-align: right;">14.6</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">45</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Vietnam</td>
<td style="text-align: right;">194</td>
<td style="text-align: right;">16.5</td>
<td style="text-align: right;">14.2</td>
<td style="text-align: right;">169</td>
<td style="text-align: right;">135</td>
</tr>
<tr class="even">
<td style="text-align: left;">India</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">74.7</td>
<td style="text-align: right;">81.1</td>
<td style="text-align: right;">173</td>
<td style="text-align: right;">132</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brazil</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">7.7</td>
<td style="text-align: right;">32.5</td>
<td style="text-align: right;">116</td>
<td style="text-align: right;">90</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thailand</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">14.3</td>
<td style="text-align: right;">51.4</td>
<td style="text-align: right;">124</td>
<td style="text-align: right;">113</td>
</tr>
</tbody>
</table>
<p>National averages overstate extreme heat where Korean plants cluster in the temperate or coastal parts of a hot country — by a factor of 3.6 in Thailand, where plants sit around Bangkok and the eastern seaboard rather than the interior, and 4.2 in Brazil. Where plants instead sit in the hotter part of the country, as in Vietnam, the national average understates the heat they face. And they understate extreme rainfall wherever plants sit on the wet coast of a country with a dry interior: China’s national five-day maximum is 59 millimetres against 145 at its plants, and the United States’ 45 against 94.</p>
<p>The discrepancy is not noise. It is the geography of where production is, and any exposure measure built from country-year data inherits it — including the trade channel of this study. For that channel the bias works against finding an effect on heat and towards finding one on flood. The plant-level results, measured at the coordinates themselves, are free of it, which is why they carry more weight than their aggregate counterparts. Supervisory frameworks that assign foreign physical risk from country-year data are assigning the wrong hazards to the wrong firms, and the direction of the error differs by hazard.</p>
</section>
<section id="damage-reaches-the-consolidated-balance-sheet-and-stops-there" class="level2">
<h2 class="anchored" data-anchor-id="damage-reaches-the-consolidated-balance-sheet-and-stops-there">3. Damage reaches the consolidated balance sheet and stops there</h2>
<p>The ownership-channel design compares a firm’s consolidated accounts, which include overseas subsidiaries, with its separate accounts, which exclude them. A shock at an overseas plant should move the first and not the second.</p>
<p>One pattern stands out. After a severe flood or drought at the principal plant, consolidated asset growth is about two percentage points lower than separate-statement growth. The components have the sign an overseas effect requires: consolidated growth falls and separate growth does not.</p>
<table class="caption-top table">
<caption>Static coefficients on the consolidated-minus-separate difference, with firm and host-country-by-year fixed effects. Wild cluster bootstrap p-values in parentheses, 474 firm clusters. The last row is a compound indicator, defined because typhoons and floods coincide in 49 percent of firm-years.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Event at principal plant</th>
<th style="text-align: right;">Δlog assets</th>
<th style="text-align: right;">ROA</th>
<th style="text-align: right;">Capex / lagged assets</th>
<th style="text-align: right;">Events</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Flood</td>
<td style="text-align: right;">−0.0215 (0.04)</td>
<td style="text-align: right;">−0.0151 (0.07)</td>
<td style="text-align: right;">−0.0270 (0.08)</td>
<td style="text-align: right;">119</td>
</tr>
<tr class="even">
<td style="text-align: left;">Drought</td>
<td style="text-align: right;">−0.0210 (0.05)</td>
<td style="text-align: right;">−0.0053 (0.29)</td>
<td style="text-align: right;">+0.0009 (0.83)</td>
<td style="text-align: right;">152</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Typhoon</td>
<td style="text-align: right;">−0.0155 (0.12)</td>
<td style="text-align: right;">−0.0019 (0.89)</td>
<td style="text-align: right;">−0.0188 (0.13)</td>
<td style="text-align: right;">183</td>
</tr>
<tr class="even">
<td style="text-align: left;">Heat</td>
<td style="text-align: right;">+0.0005 (0.97)</td>
<td style="text-align: right;">+0.0083 (0.88)</td>
<td style="text-align: right;">+0.0003 (0.98)</td>
<td style="text-align: right;">192</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Typhoon ∩ flood</td>
<td style="text-align: right;">−0.0398 (0.09)</td>
<td style="text-align: right;">−0.0389 (0.07)</td>
<td style="text-align: right;">−0.0579 (0.22)</td>
<td style="text-align: right;">64</td>
</tr>
</tbody>
</table>
<p>For flood and drought — the two hazards that move the difference — the separate-statement coefficients are small, positive and insignificant, at +0.017 and +0.001 on asset growth, while the consolidated components are negative. That contrast is the numerical basis for reading the difference as an overseas effect rather than a parent-side shock.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure2_event_study.png" class="img-fluid figure-img"></p>
<figcaption>Figure 2. Dynamic event study around a severe event at the principal overseas plant, with 95 percent confidence intervals from firm-clustered standard errors. The year before the event is k = −1. The drought pre-trend coefficient is as negative as the event coefficient, which is why the drought result is reported as weaker than the flood result.</figcaption>
</figure>
</div>
<p>This is reported as a trace rather than a finding, for three reasons stated in the paper. Of 375 coefficients in the full event-study table, 24 reach five percent against 18.8 expected under the null, and none survives a Benjamini–Hochberg correction at q = 0.05. The drought pre-trend is as negative as the event coefficient. And the compound typhoon-and-flood indicator, which carries the largest coefficients in the table, has a significant pre-trend in revenue. Only the flood pattern is clean.</p>
<p>What the shock does not do is better identified than what it does. If a two-percent decline in consolidated asset growth reflected lost production it should show in profitability; if it reflected a decision to invest less at the damaged site it should show in capital expenditure; if it reflected abandonment it should show in plant exit. It shows in none of them.</p>
<p><strong>Profitability.</strong> Pooling all four hazards gives a consolidated-minus-separate coefficient of −0.0005 (p = 0.96). Among the four single hazards the largest estimate is the flood coefficient of −0.015 (p = 0.07), and it appears with the same magnitude when the event is at a sales office rather than a plant, so it is not a production effect.</p>
<p><strong>Capital expenditure.</strong> No hazard moves it at conventional levels. Drought is a precisely estimated zero — +0.001 (p = 0.83), with a minimum detectable effect of 0.18 standard deviations — and the largest coefficient, flood at −0.027, is significant only at ten percent and does not survive the correction applied to the table. What does not respond is the investment decision itself, rather than the book value that accumulates from it.</p>
<p><strong>Plant survival.</strong> Among the 1,189 plants with exposure listed in the 2022 filings, 12.8 percent of those hit by a severe event in 2022 had disappeared from the 2024 filings, against a baseline disappearance rate of about 15 percent — so the raw comparison runs, if anything, in the hit plants’ favour. The regression estimates are no more informative in either direction: +1.8 percentage points with host-country fixed effects (p = 0.65), and −0.3 points once parent fixed effects are added (p = 0.96). The design would detect only a doubling of the exit rate, so this is the loosest bound in the ladder.</p>
<p>Taken together, the trace on consolidated assets is a write-down: damage that the accounts record and that the firm neither loses money over, responds to with investment, nor walks away from.</p>
</section>
<section id="three-placebos-separate-three-confounds-that-usually-travel-together" class="level2">
<h2 class="anchored" data-anchor-id="three-placebos-separate-three-confounds-that-usually-travel-together">4. Three placebos separate three confounds that usually travel together</h2>
<p>Earthquakes destroy productive capacity exactly as storms do but have nothing to do with climate. Consolidated statements include overseas subsidiaries while separate statements exclude them. Sales offices sit in the same countries as plants but produce nothing. The first comparison is run on the trade channel, where the outcome is capital misallocation; the second and third on the ownership channel, where the outcome is the firm’s accounts.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">Confound it removes</th>
<th style="text-align: left;">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Earthquakes vs.&nbsp;climate hazards (trade channel)</td>
<td style="text-align: left;">Any effect of disaster exposure as such</td>
<td style="text-align: left;">Null at equal precision: +0.017, bootstrap p = 0.64, at 0.28σ</td>
</tr>
<tr class="even">
<td style="text-align: left;">Consolidated vs.&nbsp;separate statements</td>
<td style="text-align: left;">Parent-side shocks correlated with plant location</td>
<td style="text-align: left;">Signal in consolidated, not separate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Plants vs.&nbsp;sales offices</td>
<td style="text-align: left;">Any “overseas presence” effect unrelated to production</td>
<td style="text-align: left;">Null at sales offices; typhoon at equal power</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure3_plant_vs_sales.png" class="img-fluid figure-img"></p>
<figcaption>Figure 3. Principal plant versus principal sales office, static coefficients on consolidated-minus-separate outcomes with 95 percent confidence intervals. At sales offices the asset-growth coefficients are zero or positive, the ROA coefficients match the plant ones, and capital expenditure is null throughout. The placebo is underpowered for flood and drought — its minimum detectable effects are two to three times the plant coefficient — but at equal power for typhoons, where it is null.</figcaption>
</figure>
</div>
<p>The asset-growth trace passes the second test. The nulls on profits and investment pass all three.</p>
</section>
<section id="through-the-trade-channel-the-shock-arrives-as-a-fifth-of-a-percent" class="level2">
<h2 class="anchored" data-anchor-id="through-the-trade-channel-the-shock-arrives-as-a-fifth-of-a-percent">5. Through the trade channel the shock arrives as a fifth of a percent</h2>
<p>The qualitative claim that sourcing is diversified, so shocks are diluted, leaves the quantitative question unanswered. Every term in the following calculation is estimated rather than assumed.</p>
<p>Foreign value added is 32.8 percent of Korean manufacturing gross output. Within that foreign component the largest single origin averages 23.5 percent across industries. And a one standard deviation increase in a partner country’s drought exposure reduces Korean imports from it by 2.8 percent. Whether that decline reflects supply disruption or a contraction in the partner economy does not matter for the arithmetic: either way it is the reduction in inputs Korean industry actually experiences. The three magnitudes multiply:</p>
<p><span class="math display">\[0.328 \times 0.235 \times 0.0284 = 0.22 \text{ percent}.\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure4_value_added_origin.png" class="img-fluid figure-img"></p>
<figcaption>Figure 4. Origin of the foreign value added embodied in Korean manufacturing output, 2020–2024. China contributes the largest single share at 19 percent of the foreign component, the United States 14 percent and Japan 7 percent, with the remainder spread across some sixty economies. Economies in grey fall inside the input–output tables’ rest-of-world aggregate and cannot be attributed individually. Exposure is concentrated but not dominated, which is what makes the dilution above arithmetic rather than incidental.</figcaption>
</figure>
</div>
<p>Suppose instead, counterfactually, that every foreign supplier were struck simultaneously by a one standard deviation drought. Dropping the concentration term gives 0.93 percent. Even that upper bound leaves the input bill essentially unmoved.</p>
<p>The sourcing structure behind the dilution is visible directly in customs records linked to the business register. The value-weighted average number of partner countries is between 18 and 23 in five of seven industry groups and 13.1 in a sixth, and firms trading with ten or more partners account for roughly 75 percent of manufacturing imports. One industry departs sharply: textiles and leather averages 8.5 partners, with a fifth of its imports coming from single-partner firms.</p>
<p>The natural alternative account — that firms notice climate stress and re-source, as Pankratz and Schiller (2024) find of supplier relationships and Blaum, Esposito and Heise (2026) of US manufacturers’ sourcing — is testable here and fails. Trade with drought-stressed countries does fall, but imports and exports fall by the same amount, which is the signature of a contraction in the partner economy rather than of reallocation by Korean buyers. For the other hazards neither direction moves at all.</p>
<table class="caption-top table">
<caption>Log Korean import value from the partner, log export value to it, and their log ratio, per standard deviation of exposure. Industry-by-year and industry-by-country fixed effects; bootstrap p-values in parentheses. Import-specific reallocation in trade value larger than about two percent is ruled out for every hazard.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Hazard</th>
<th style="text-align: right;">Imports</th>
<th style="text-align: right;">Exports</th>
<th style="text-align: right;">Import/export ratio</th>
<th style="text-align: right;">MDE (ratio)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Drought</td>
<td style="text-align: right;">−0.0284 (0.027)</td>
<td style="text-align: right;">−0.0282 (0.010)</td>
<td style="text-align: right;">−0.0008 (0.961)</td>
<td style="text-align: right;">0.017</td>
</tr>
<tr class="even">
<td style="text-align: left;">Heat &gt;35°C</td>
<td style="text-align: right;">−0.0064 (0.605)</td>
<td style="text-align: right;">−0.0072 (0.495)</td>
<td style="text-align: right;">+0.0010 (0.909)</td>
<td style="text-align: right;">0.011</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flood</td>
<td style="text-align: right;">+0.0006 (0.976)</td>
<td style="text-align: right;">+0.0002 (0.992)</td>
<td style="text-align: right;">−0.0010 (0.953)</td>
<td style="text-align: right;">0.021</td>
</tr>
</tbody>
</table>
<p>One import-side pattern survives. Heat reduces the number of Korean firms importing from a stressed partner by 0.67 percent without reducing the value imported and without moving exports, which implies consolidation among larger importers rather than reallocation across countries. The paper reports it and builds nothing on it.</p>
<p>Absorption here is a property of how sourcing is organised, not of how firms respond. A firm drawing on twenty origins has little reason to act, precisely because a disaster in any one of them moves a small share of its input bill.</p>
</section>
<section id="most-hazards-are-precise-nulls-and-flood-is-the-exception" class="level2">
<h2 class="anchored" data-anchor-id="most-hazards-are-precise-nulls-and-flood-is-the-exception">6. Most hazards are precise nulls, and flood is the exception</h2>
<p>A null is worth only the bound it carries. Minimum detectable effects — the smallest coefficient the design would reject against, at five percent significance and eighty percent power — vary by a factor of seven across hazards, so a single summary figure would misrepresent the evidence.</p>
<table class="caption-top table">
<caption>A selection of the sixteen rows the paper reports, ordered by precision. The dependent variable is the within-industry dispersion of log marginal revenue products of capital, built from 1.11 million establishment-year observations following Hsieh and Klenow (2009).</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Hazard measure</th>
<th style="text-align: right;">MDE (σ of outcome)</th>
<th style="text-align: left;">Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Maximum wind speed</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: left;">precise null</td>
</tr>
<tr class="even">
<td style="text-align: left;">Drought events</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: left;">precise null</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Storm count, typhoon count</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: left;">see below</td>
</tr>
<tr class="even">
<td style="text-align: left;">Drought, consecutive dry days</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: left;">precise null</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Power dissipation index, ACE</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: left;">precise null</td>
</tr>
<tr class="even">
<td style="text-align: left;">Heat, days &gt;40°C</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: left;"><strong>effect found</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flood events</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: left;">moderate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Heat, days &gt;35°C</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: left;"><strong>effect found</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flood, days precip. &gt;20 mm</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: left;">weak</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flood, max. 5-day precipitation</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: left;">weak</td>
</tr>
</tbody>
</table>
<p>The precipitation-based flood measures are the one place the table licenses no conclusion — 0.44σ and 0.49σ, against 0.26σ for the measure built from counts of realised flood disasters — and since floods are the hazard most often assumed to disrupt supply chains, the paper pursues them. The imprecision turns out to be mechanical and remediable: essentially all of the inflation in the clustered standard error comes from coke and refined petroleum, the industry whose exposure measure covers the smallest share of actual sourcing. Excluding it cuts the flood standard error from 0.049 to 0.021 and the minimum detectable effect from 0.49σ to 0.25σ — from roughly ten percent of the dispersion to 4.2 percent — with the point estimate still indistinguishable from zero. A second and independent correction, replacing the precipitation proxy with the disaster counts on the full sample, lands at 0.26σ. That two different corrections converge is more reassuring than either alone, and the paper nonetheless keeps the conservative 0.49σ in its headline bound.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure5_hazard_coefficients.png" class="img-fluid figure-img"></p>
<figcaption>Figure 5. Estimated effect of each hazard on capital misallocation, with 68 and 95 percent confidence intervals. Exposure is standardised, so coefficients are responses to a one standard deviation change. Most point estimates are negative — the opposite sign to what a disruption channel predicts. The earthquake placebo in black is null at essentially the same precision as the 35°C heat measure.</figcaption>
</figure>
</div>
<p>The storm measures are the paper’s most instructive non-finding. Lined up by how heavily they weight intensity — a raw count treats all storms alike, a typhoon count applies a threshold, maximum wind takes the peak, and the accumulated-energy and dissipation indices weight by V² and V³ — the bootstrap p-values rise monotonically along that ordering: 0.019, 0.145, 0.320, 0.479, 0.553.</p>
<p>If wind damage were transmitting to Korean capital allocation, the gradient would run the other way: damage scales with dissipated power, so the V³ measure should carry the signal. The reverse is observed. The measure with no intensity information is significant at conventional levels — though not after correction for the nineteen hazard measures reported — with a negative sign that no disruption mechanism predicts, and the measure that best represents damage is the weakest in the table. The reader who suspects a strengthening cyclone could damage a supplier without producing a flood can be answered directly: that channel is measured at the intensity where damage occurs, and an effect above roughly a tenth of a standard deviation is ruled out.</p>
</section>
<section id="extreme-heat-is-where-the-evidence-divides" class="level2">
<h2 class="anchored" data-anchor-id="extreme-heat-is-where-the-evidence-divides">7. Extreme heat is where the evidence divides</h2>
<p>Heat produces the largest coefficients in the table and the only significant ones with the sign a disruption channel predicts: +0.069 for days above 35°C and +0.053 for days above 40°C, per standard deviation of exposure. Most point estimates in the table are negative, and the two positive flood coefficients are indistinguishable from zero. The heat coefficients deserve scrutiny rather than either dismissal or acceptance, and they pass three filters and fail three.</p>
<p><strong>They pass.</strong> Under a multiple-testing correction defined at the level of hazards — seven families rather than each individual measure — both clear the Bonferroni and Benjamini–Hochberg thresholds. Defined instead at the level of all nineteen individual measures, neither clears: the 40°C estimate fails Bonferroni at p = 0.003 against a threshold of 0.0026, the 35°C estimate at p = 0.007, and Benjamini–Hochberg at a five percent false discovery rate rejects nothing. The paper reports both answers rather than the more favourable one, and rests the claim on neither. The threshold measures do enter positively on all three outcome variables, with p-values between 0.021 and 0.105 — though two other heat measures fail to cooperate, and the paper says so: the annual maximum temperature is insignificant (p = 0.120) and the EM-DAT extreme-temperature event count carries the opposite sign (−0.026, p = 0.325), so the result rests on the two reanalysis threshold counts alone. And the geophysical placebo holds: earthquake exposure, constructed identically, gives +0.017 with a bootstrap p of 0.642, at a precision of 0.28σ against the heat measure’s 0.27σ. It has the power to find an effect of the size heat produces, and finds nothing.</p>
<p><strong>They fail.</strong> Three checks cut the other way, and the paper states the pattern plainly: the association holds for one supplier country, under one of two defensible normalisations of exposure, and under one of two defensible standardisations of the hazard.</p>
<p>The first is origin. Splitting exposure into the Chinese component and everything else puts the entire effect in China: +0.0859 (p = 0.039) against +0.0063 (p = 0.766). This is not a power failure — the non-China component is estimated more precisely, and its confidence interval of [−0.036, 0.049] excludes an effect of China’s magnitude. Nor is it an artefact of a single industry: dropping each of the fourteen industries in turn leaves the 35°C coefficient between 0.048 and 0.091, significant in all fourteen cases.</p>
<p>Inside that first break sits a sharper problem. If heat damages production, the effect should be strongest where suppliers are hottest. Splitting three ways gives the opposite ordering.</p>
<table class="caption-top table">
<caption>Hot suppliers are those averaging at least five days above 35°C, some 21 percent of foreign value added: India (78.7 days), Australia (80.2), Thailand (43.6), Brazil (22.1), the United States (12.5) and Vietnam (10.0). Temperate suppliers include Japan (0.6), Germany (0.3), the United Kingdom and Taiwan (both ≈ 0). Classification uses long-run levels and was fixed before estimation.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Component</th>
<th style="text-align: right;">Days &gt;35°C (long-run mean)</th>
<th style="text-align: right;">β</th>
<th style="text-align: right;">Boot. p</th>
<th style="text-align: right;">MDE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">China</td>
<td style="text-align: right;">5.8</td>
<td style="text-align: right;">+0.0711</td>
<td style="text-align: right;">0.042</td>
<td style="text-align: right;">0.33σ</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other hot suppliers</td>
<td style="text-align: right;">high</td>
<td style="text-align: right;">−0.0373</td>
<td style="text-align: right;">0.185</td>
<td style="text-align: right;">0.24σ</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Temperate suppliers</td>
<td style="text-align: right;">≈ 0</td>
<td style="text-align: right;">+0.0361</td>
<td style="text-align: right;">0.098</td>
<td style="text-align: right;">0.17σ</td>
</tr>
</tbody>
</table>
<p>A heat mechanism predicts hot &gt; China &gt; temperate. The data give China &gt; temperate &gt; hot, and the hot-supplier component is estimated at better precision than China’s own. Two facts therefore hold simultaneously: within China the association is specific to heat rather than to Chinese years in general, and across countries it bears no relation to how much heat suppliers actually experience. The paper does not reconcile them.</p>
<p>The second break is normalisation. The estimate does not survive replacing the renormalised exposure measure with the unnormalised one (p = 0.831 and 0.587), and controlling separately for the foreign value-added share does not restore it (−0.032, p = 0.802) while leaving the renormalised coefficient untouched (+0.057, p = 0.003). The obvious conjecture is therefore rejected, and the paper reports that it has no account of why the two constructions differ so sharply.</p>
<p>The third is standardisation of the hazard. Measured in days rather than standardised anomalies the coefficient reverses sign and loses significance, whereas the drought and flood nulls are entirely insensitive to the same choice. The sensitivity is specific to heat, which is the only hazard whose measure is a threshold count with near-degenerate baselines.</p>
<p>The plant-level test cannot settle it either. At plant coordinates, where no standardisation across countries is needed, heat is absent — but Korean plants sit where days above 40°C are rare, so that test is weak by construction. The paper’s own verdict is that it does not claim imported heat propagates and does not claim it does not; what the design establishes is the bound, and heat is the one hazard whose checks disagree among themselves.</p>
</section>
<section id="the-boundary-of-what-the-current-evidence-supports" class="level2">
<h2 class="anchored" data-anchor-id="the-boundary-of-what-the-current-evidence-supports">8. The boundary of what the current evidence supports</h2>
<p><strong>Established.</strong> A severe flood or drought at a firm’s principal overseas plant leaves a trace of about two percentage points on consolidated asset growth, absent from the parent’s separate statements — though it does not survive a false-discovery correction, and the sales-office placebo is underpowered for precisely these two hazards, so it is the consolidated-versus-separate contrast and not the plant-versus-sales-office one that carries this result. National-aggregate exposure overstates the heat that plants face by a factor of three to four wherever plants cluster in the temperate or coastal parts of a hot country, and understates their extreme rainfall wherever they sit on a wet coast, because production sits on coasts and in river basins. A one-σ drought in an industry’s largest foreign origin reaches the input bill as 0.22 percent, and trade with a drought-stressed partner falls symmetrically in both directions.</p>
<p><strong>Ruled out.</strong> That the trace reflects lost production, a disinvestment decision, or abandonment — profitability, capital expenditure and plant survival are null, and the capex null is tight, with a minimum detectable effect of 0.18σ on the drought estimate. The one residual is flood, where ROA is −0.015 (p = 0.07) and capex −0.027 (p = 0.08); the flood ROA coefficient appears at the same magnitude when the event is at a sales office, which is why the paper does not read it as a production effect. That Korean firms re-source away from climate-stressed suppliers: import-specific reallocation in trade value above about two percent is excluded for every hazard. That foreign physical risk moves the allocation of capital across domestic establishments: effects above two percent of dispersion are excluded for storms, drought and landslide, and above four to five percent for flood once the petroleum sector’s noise is removed. And that the effect is disaster exposure in general rather than climate — earthquakes are null at equal precision.</p>
<p><strong>Still admissible.</strong> Amplification through production networks — of the kind Baqaee and Farhi (2019) formalise and Barrot and Sauvagnat (2016) and Boehm, Flaaen and Pandalai-Nayar (2019) document — may operate at a scale below what this design bounds. Smaller firms, which are less likely to hold insurance, inventories or alternative sites, may respond differently; the sample is listed manufacturers with disclosed subsidiaries. Disruptions that depress one quarter and are recovered within the fiscal year leave no trace in annual accounts, so the asset trace is a lower bound on transient damage. And heat may yet matter through a mechanism this design misreads.</p>
<p><strong>Unresolved.</strong> Whether the heat association is a climate effect at all, given that it is confined to one supplier country and runs opposite to supplier climate elsewhere. Which of insurance recoveries, production shifted to other sites, or inventories does the absorbing on the ownership side — all three are consistent with a write-down that leaves profits untouched, and the data do not distinguish among them. And the unexplained negative storm-count coefficient, stable across all three outcomes but contradicted by every intensity-weighted measure of the same hazard.</p>
</section>
<section id="finer-resolution-not-a-longer-sample" class="level2">
<h2 class="anchored" data-anchor-id="finer-resolution-not-a-longer-sample">9. Finer resolution, not a longer sample</h2>
<p>None of the limits above would be removed by more years of the same data. Each points to a different source of information.</p>
<p><strong>Sub-annual outcomes.</strong> Quarterly or monthly accounts would detect the disruption that annual statements average away, and would turn the lower bound on transient damage into an estimate.</p>
<p><strong>Firm-level sourcing.</strong> Dispersion of marginal revenue products within an industry is invariant to a shock that hits every establishment equally. Customs records linked to the business register at the firm-by-partner-country level would let exposure vary within an industry, which is what the outcome measure requires and what country-year data cannot supply.</p>
<p><strong>Insurance claims and inventory records.</strong> These would separate the three candidate absorption mechanisms on the ownership side, which the accounts alone cannot.</p>
<p><strong>More clusters, not a better measure.</strong> For heat the paper regards the measurement problem as solved and the sample problem as open: plant coordinates remove both sources of ambiguity in the country-year measure, and the remaining constraint is that fourteen industry clusters over fifteen years is thin for an effect worth a few percent of dispersion. Firm-level sourcing data would raise the cluster count by orders of magnitude. Plant-level output for Korean sites in the few genuinely hot host countries would do the same for the ownership-side test, which is weak only because those plants rarely see days above 40°C.</p>
<p><strong>The price of the buffer.</strong> The margin on which the shock is absorbed — diversified sourcing on the trade side, and whatever combination of insurance, inventories and alternative sites on the ownership side — is itself costly to maintain. That cost is the part of imported physical risk this design does not price, and the part a supervisor would most want to know.</p>
</section>
<section id="working-paper" class="level2">
<h2 class="anchored" data-anchor-id="working-paper">Working paper</h2>
<p>The working paper reports the full estimating equations, the geocoding pipeline and its validation, the construction of both exposure measures, the complete grid of every outcome the establishment microdata supports against every hazard, and the robustness checks behind each bound, with an appendix that includes the negative results and the abandoned specifications.</p>
<p><a href="https://khdouble.github.io/files/wp/imported-physical-climate-risk-supply-chains.pdf">Download the PDF</a></p>
<section id="suggested-citation" class="level3">
<h3 class="anchored" data-anchor-id="suggested-citation">Suggested citation</h3>
<blockquote class="blockquote">
<p>Kim, Hyun Hak (2026). “Where Imported Physical Climate Risk Stops: Supply Chains, Overseas Plants, and the Manufacturing Balance Sheet.” Working Paper, September 1.</p>
</blockquote>
</section>
<section id="data-and-code" class="level3">
<h3 class="anchored" data-anchor-id="data-and-code">Data and code</h3>
<p>The analysis combines public and restricted sources. Subsidiary disclosures come from the Financial Supervisory Service’s <a href="https://dart.fss.or.kr">DART</a> filings; daily weather from ERA5 and ERA5-Land; cyclone tracks from IBTrACS; disaster records from EM-DAT, whose terms do not permit redistribution; input–output tables from the Asian Development Bank; and trade statistics from Statistics Korea. The establishment panel is microdata of the Mining and Manufacturing Survey, a census of establishments with ten or more employees, obtained through Statistics Korea’s <a href="https://mdis.kostat.go.kr">Microdata Integrated Service</a>, whose terms of use likewise do not permit redistribution.</p>
<p>Code and replication materials will be released with the published version of the paper. Until then, requests for academic replication or verification are handled individually. Please write to <a href="mailto:hyunhak.kim@kookmin.ac.kr">hyunhak.kim@kookmin.ac.kr</a>.</p>
</section>
<section id="funding" class="level3">
<h3 class="anchored" data-anchor-id="funding">Funding</h3>
<p>This research was supported by the Graduate School Specialized in Climate Change, funded by the Ministry of Climate, Energy and Environment (MCEE).</p>
</section>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<p>Baqaee, D. R. and Farhi, E. (2019). The macroeconomic impact of microeconomic shocks: beyond Hulten’s theorem. <em>Econometrica</em>, 87(4), 1155–1203.</p>
<p>Barrot, J.-N. and Sauvagnat, J. (2016). Input specificity and the propagation of idiosyncratic shocks in production networks. <em>Quarterly Journal of Economics</em>, 131(3), 1543–1592.</p>
<p>Blaum, J., Esposito, F. and Heise, S. (2026). Input sourcing under climate risk: evidence from U.S. manufacturing firms. <em>Review of Economic Studies</em>, forthcoming.</p>
<p>Boehm, C. E., Flaaen, A. and Pandalai-Nayar, N. (2019). Input linkages and the transmission of shocks: firm-level evidence from the 2011 Tōhoku earthquake. <em>Review of Economics and Statistics</em>, 101(1), 60–75.</p>
<p>Hsieh, C.-T. and Klenow, P. J. (2009). Misallocation and manufacturing TFP in China and India. <em>Quarterly Journal of Economics</em>, 124(4), 1403–1448.</p>
<p>Pankratz, N. M. C. and Schiller, C. (2024). Climate change and adaptation in global supply-chain networks. <em>Review of Financial Studies</em>, 37(6), 1729–1777.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/khdouble\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© Hyun Hak Kim · Department of Economics, Kookmin University</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>