<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-10-05">
<meta name="description" content="Stablecoin issuers hold the Treasury bills that banks hold to meet the liquidity coverage ratio. Modelled as the rule works in practice, the premium on bank collateral starts rising when the stock of coins is about twice today’s, well before the regulatory threshold; bills crowd out about 2.4 times as much as bank deposits; and discount-window readiness and a recycled Federal Reserve deposit share beat an issuance cap at every stock.">

<title>Coins Made of Bank Collateral – Hyun Hak Kim</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-0b873dab1a9bb082c1df6b2c2700682a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-d7d8c43c9bbf52025258093b17e489d4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-0b873dab1a9bb082c1df6b2c2700682a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,400;8..60,600;8..60,700&amp;display=swap">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css">


<meta property="og:title" content="Coins Made of Bank Collateral – Hyun Hak Kim">
<meta property="og:description" content="Stablecoin issuers hold the Treasury bills that banks hold to meet the liquidity coverage ratio. Modelled as the rule works in practice, the premium on bank collateral starts rising when the stock of coins is about twice today’s, well before the regulatory threshold; bills crowd out about 2.4 times as much as bank deposits; and discount-window readiness and a recycled Federal Reserve deposit share beat an issuance cap at every stock.">
<meta property="og:image" content="https://khdouble.github.io/posts/2026-10-stablecoin-bank-collateral-en/figures/figure1_crowding_out_zone.png">
<meta property="og:site_name" content="Hyun Hak Kim">
<meta property="og:image:height" content="703">
<meta property="og:image:width" content="1616">
<meta property="og:image:alt" content="Premium on safe assets and change in bank lending against the total stock of US dollar stablecoins, for the observed reserve mix and for reserves held as bank deposits">
</head>

<body class="nav-sidebar docked article quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      Hyun Hak Kim
      </li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Hyun Hak Kim</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="../../files/cv-hyunhak-kim.pdf" title="Curriculum Vitae" class="quarto-navigation-tool px-1" aria-label="Curriculum Vitae"><i class="bi bi-file-earmark-text"></i></a>
    <a href="mailto:hyunhak.kim@kookmin.ac.kr" title="Email" class="quarto-navigation-tool px-1" aria-label="Email"><i class="bi bi-envelope"></i></a>
    <a href="https://www.linkedin.com/in/khdouble/" title="LinkedIn" class="quarto-navigation-tool px-1" aria-label="LinkedIn"><i class="bi bi-linkedin"></i></a>
    <a href="https://github.com/khdouble" title="GitHub" class="quarto-navigation-tool px-1" aria-label="GitHub"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Research</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../blog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Blog</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../links.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Links</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#the-question" id="toc-the-question" class="nav-link active" data-scroll-target="#the-question">The question</a></li>
  <li><a href="#five-findings" id="toc-five-findings" class="nav-link" data-scroll-target="#five-findings">Five findings</a></li>
  <li><a href="#the-evidence-in-brief" id="toc-the-evidence-in-brief" class="nav-link" data-scroll-target="#the-evidence-in-brief">The evidence in brief</a></li>
  <li><a href="#where-the-results-are-conditional" id="toc-where-the-results-are-conditional" class="nav-link" data-scroll-target="#where-the-results-are-conditional">Where the results are conditional</a></li>
  <li><a href="#what-it-means-for-the-rules-being-written" id="toc-what-it-means-for-the-rules-being-written" class="nav-link" data-scroll-target="#what-it-means-for-the-rules-being-written">What it means for the rules being written</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Coins Made of Bank Collateral</h1>
<p class="subtitle lead">Where US stablecoin reserves start to crowd out the collateral banks hold for liquidity rules, and which of the rules now being written would help</p>
  <div class="quarto-categories">
    <div class="quarto-category">English</div>
    <div class="quarto-category">Stablecoins</div>
    <div class="quarto-category">Bank Regulation</div>
  </div>
  </div>

<div>
  <div class="description">
    Stablecoin issuers hold the Treasury bills that banks hold to meet the liquidity coverage ratio. Modelled as the rule works in practice, the premium on bank collateral starts rising when the stock of coins is about twice today’s, well before the regulatory threshold; bills crowd out about 2.4 times as much as bank deposits; and discount-window readiness and a recycled Federal Reserve deposit share beat an issuance cap at every stock.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 5, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Working paper</strong> — <a href="https://khdouble.github.io/files/wp/stablecoins-crowd-out-bank-collateral.pdf">When Do Stablecoins Crowd Out Bank Collateral?</a> (October 2026 draft).</p>
</div>
</div>
</div>
<section id="the-question" class="level2">
<h2 class="anchored" data-anchor-id="the-question">The question</h2>
<p>Dollar stablecoins outstanding reached $311 billion in October 2026, and their issuers hold reserves almost entirely in Treasury bills, bill-backed repo and government money funds — about $200 billion of bills and bill repo at the end of 2025. The Treasury’s advisory committee projects $2 trillion of coins and $1 trillion of issuer bill holdings by 2028. The same bills are the high-quality liquid assets that banks hold against stressed outflows under the liquidity coverage ratio. The twenty-one US bank holding companies subject to the ratio disclose $4.54 trillion of such assets against $3.91 trillion of net 30-day outflows: a slack of $630 billion. The stock of coins was negligible against that slack in 2019; it is now 32 percent of the stock at which the slack would be used up.</p>
<p>The paper asks when issuance starts to crowd out the collateral banks hold for liquidity, what that does to bank credit, and which of the rules now being written — on issuers’ reserves, on the deposits they place with banks, and on the banks that receive them — would help. The existing answer, in the models of Hofmann, Kaldorf and Rottner (2026) and the evidence of Ahmed and Aldasoro (2026), is a price channel with a small effect on lending. The paper shows that this is the early part of a longer schedule once the liquidity rule is modelled as it works: a bank must meet the ratio every business day, so it holds a buffer, buys compliance with term funding or at the discount window — at the window’s spread plus the stigma of borrowing — up to the collateral it can pledge, and deleverages beyond that. Each cost is a probability times a unit cost, so the value of a safe asset to the banking system rises smoothly as the slack falls, not at a cliff. The stock of coins is not a parameter but what households demand at the bill yield the model itself produces. The model is calibrated to October 2026 data, and its predictions are checked against issuer attestations, banks’ liquidity disclosures, call reports and weekly bill yields.</p>
<section id="headline-figures" class="level3">
<h3 class="anchored" data-anchor-id="headline-figures">Headline figures</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Stablecoins outstanding, October 2026</td>
<td style="text-align: right;">$311 billion</td>
</tr>
<tr class="even">
<td style="text-align: left;">Disclosed liquidity slack of the 21 banks under the ratio, 2026Q2</td>
<td style="text-align: right;">$630 billion</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Premium on bank collateral: today / 25 bp / regulatory threshold / 100 bp</td>
<td style="text-align: right;">3 bp / $661 bn / $961 bn (86 bp) / $1,036 bn</td>
</tr>
<tr class="even">
<td style="text-align: left;">With $1 trillion of new issuance: premium, lending, as bills (as bank deposits)</td>
<td style="text-align: right;">158 bp, −$64 bn (67 bp, −$26 bn)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Largest demand the system absorbs, observed reserve mix</td>
<td style="text-align: right;">$1,949 billion; $2.0–3.1 trillion if issuers rebalance; none if holders compare coins with deposit rates</td>
</tr>
<tr class="even">
<td style="text-align: left;">Welfare gain at $1 trillion of demand: Fed deposits (recycled) / discount-window readiness / deposit reserves / cap</td>
<td style="text-align: right;">+1.3 / +1.3 / +1.2 / −3.0 $ billion a year</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Banks holding Circle’s cash before March 2023 that were subject to the ratio</td>
<td style="text-align: right;">0 of 6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bill-buying issuer dollars, three-month bill yield after four weeks (non-bill dollars)</td>
<td style="text-align: right;">−11 to −19 bp per $3.5 bn (no decline)</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="five-findings" class="level2">
<h2 class="anchored" data-anchor-id="five-findings">Five findings</h2>
<p><strong>1. Crowding out begins well before the regulatory threshold.</strong> The premium on safe assets is 3 basis points at today’s stock. It reaches 25 basis points at a total stock of $661 billion — about twice today’s — and 86 at the threshold of $961 billion, where the disclosed slack is used up. The threshold is the midpoint of the crowding-out zone, not its start. With $1 trillion of new issuance the premium is 158 basis points, bank lending is $64 billion lower and the expected cost of stress liquidations is $4.1 billion a year.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure1_crowding_out_zone.png" class="img-fluid figure-img"></p>
<figcaption>Figure 1. The crowding-out zone, US calibration. (a) Premium on safe assets against the total stock of stablecoins, for the observed reserve mix and for the same reserves held as bank deposits. (b) Change in bank lending. Vertical lines mark today’s stock, the regulatory threshold at which the disclosed slack is used up, and the 2028 projection.</figcaption>
</figure>
</div>
<p><strong>2. Bills crowd out more than bank deposits.</strong> A bill purchase removes a unit of collateral from the banking system. An issuer deposit makes the receiving bank hold safe assets against it — a bank funded mainly by issuer deposits becomes a narrow bank — but adds only its actual run-off to stress outflows. With $1 trillion of new issuance held as bank deposits instead of bills, the premium is 67 basis points rather than 158 and the lending loss $26 billion rather than $64 billion: bills crowd out 2.4 times as much. Competitive pricing already points issuers the same way: once collateral is scarce, banks pay more for issuer deposits than bills return (by 55 basis points at the $1 trillion level), so issuers that rebalance absorb less. Today they hold 4.6 percent of reserves as bank deposits.</p>
<p><strong>3. There can be a largest demand the system absorbs.</strong> Coin demand rises as bill yields fall, and collateral scarcity lowers bill yields, so one more coin draws in further coins. While the premium path is gentle the feedback is damped; once banks’ term-funding capacity is exhausted and deleveraging steepens the path, one coin can draw in more than one further coin, and issuance growing from today’s stock no longer settles. With the observed reserve mix that point — the fold — is at a demand of $1,949 billion, just short of the 2028 projection. It is a conditional result: if issuers rebalance toward deposits as deposit pricing leads them to, the fold moves to $2.0–3.1 trillion; discount-window readiness moves it to $3.6 trillion; and if coin holders compared coins with a bank deposit rate rather than a money-market yield, there would be no fold at all. What does not depend on these assumptions is that the premium rises steeply well before it.</p>
<p><strong>4. Instruments that change what a coin absorbs beat instruments that remove coins.</strong> Against current rules, at $1 trillion of demand, a requirement to hold part of the reserves at the Federal Reserve — an asset the GENIUS Act already permits — gains $1.3 billion a year <em>if the Federal Reserve lends the funds back to banks</em>, and nothing if it does not; discount-window readiness, under which every bank pre-pledges collateral for 90 percent of its outflows, gains $1.3 billion, so the two are tied; reserves held as bank deposits gain $1.2 billion; an issuance cap at the threshold loses $3.0 billion. At $2 trillion with a bill supply that responds to the price, the gains are $15.2, $12.3 and $11.3 billion and the cap loses $81 billion. The Federal Reserve deposit share leads at that level only if more than 94.6 percent of the deposits are recycled and holding them costs the Federal Reserve less than 21 basis points a year; discount-window readiness needs no such condition. The cap lowers welfare wherever it binds, in every calibration, because it rations coins that households demand.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure2_instruments.png" class="img-fluid figure-img"></p>
<figcaption>Figure 2. Instruments against current rules, US calibration. Welfare gain over current rules by instrument: (a) at the regulatory threshold and at the $1 trillion demand level with a fixed bill supply; (b) at the $2 trillion demand level with a bill supply that responds to the price.</figcaption>
</figure>
</div>
<p><strong>5. The run-off rate and the concentration limit address a different problem, and the wrong quantity.</strong> A run-off rate on issuer deposits and the FDIC’s proposed 40 percent limit on an issuer’s exposure to any one bank do nothing for collateral while issuers hold bills. Their case is the run on the issuer that forces its partner bank to raise cash, and there the binding quantity is the partner bank’s equity. A specialist partner with $1.2 billion of equity, modelled on the crypto-focused banks of 2022, cannot be protected by any run-off rate beyond $24–32 billion of issuer deposits: the fire-sale loss on the cover it would have to sell, and the loans it would then have to liquidate, exhaust its equity. A 40 percent cap written on the issuer’s side protects such a bank only up to $60–79 billion of issuance; at the size of the largest issuer today, the per-bank limit that would protect it is 13–17 percent. A limit that scales with the receiving bank’s equity, whatever its regulatory category, does the work that neither a uniform rate nor a uniform cap can do — the paper’s answer to Question 59 of the FDIC’s proposal.</p>
</section>
<section id="the-evidence-in-brief" class="level2">
<h2 class="anchored" data-anchor-id="the-evidence-in-brief">The evidence in brief</h2>
<p>The public record lines up with the model’s structure, though none of it is a causal test. Every bank that held Circle’s cash before March 2023 — Silicon Valley Bank, Signature, Silvergate, Customers, New York Community and Citizens Trust — was outside the liquidity coverage ratio, which is where the model’s deposit pricing sends issuer deposits: a bank outside the ratio can lend part of them and pay more. Silvergate, the bank whose funding was dominated by such deposits, held cash and securities equal to 0.87 of its assets against a peer median of 0.27 and a loan share 55 points below its peers; it operated as a narrow bank, and the liquidity it held implies a run-off of 0.74 on those deposits. The model’s capital condition, evaluated with balance sheets public before the run, singles out Silvergate — digital-asset deposits 10.7 times its equity, failure at any fire-sale discount above 10 percent, a realized discount of 13.8 percent — and clears Signature (threshold 0.39) and Silicon Valley Bank, where Circle’s deposit was covered by cash and the failure ran the other way, from the bank to the issuer. The banks under the ratio have kept it above 1.04 in every quarter since 2018, as a probabilistic compliance cost implies. And in weekly data, issuer dollars that buy bills lower the three-month bill yield by 11–19 basis points per $3.5 billion for a few weeks, while the same issuers’ repo and deposit dollars do not; a lending response to issuer absorption is not detectable in the observed range, where the model predicts it to be negligible, but the estimates are imprecise.</p>
</section>
<section id="where-the-results-are-conditional" class="level2">
<h2 class="anchored" data-anchor-id="where-the-results-are-conditional">Where the results are conditional</h2>
<p>The threshold pools the slack across banks and assumes a collateral market that works without friction — the assumption that failed in September 2019; if slack did not move at all, the lowest-ratio bank would reach its floor after $225 billion of bill-backed issuance. The fold needs a demand response to bill yields (the estimated semi-elasticity has an interval that includes zero) and depends on the alternative coin holders compare coins with; the issuers’ reallocation response is proxied by Circle’s response between bills and repo. The model has one safe asset and does not separate reserves from bills, which the 2019 episode says matters. The bank-level evidence measures where issuer deposits sat and how they were held; it does not identify a causal effect.</p>
</section>
<section id="what-it-means-for-the-rules-being-written" class="level2">
<h2 class="anchored" data-anchor-id="what-it-means-for-the-rules-being-written">What it means for the rules being written</h2>
<ul>
<li><strong>Composition matters more than quantity.</strong> The assets the GENIUS Act permits differ by a factor of about 2.4 in how much bank collateral a dollar of reserves removes, and deposit pricing already pushes issuers toward the assets that remove less.</li>
<li><strong>A Federal Reserve deposit option for issuers is worth having only if the funds are lent back to banks</strong>, almost in full; sterilized, it withdraws bank funding and is worth nothing.</li>
<li><strong>Discount-window readiness</strong> — collateral pre-pledged against stressed outflows, which the Federal Reserve has urged on banks since 2023 — is the one instrument that helps without a condition, and it moves the point at which issuance stops settling the furthest.</li>
<li><strong>An issuance cap lowers welfare at every stock</strong>: it rations a product households want to protect a collateral price that other instruments protect more cheaply.</li>
<li><strong>For the run risk, limit the receiving bank, not the issuer</strong>: a per-bank limit scaled to the bank’s equity, applied whatever its regulatory category, since the banks that held issuer deposits in 2023 were the ones the liquidity rules did not reach.</li>
<li><strong>What to watch</strong>: the aggregate slack of the banks under the ratio, and the stock of coins relative to the room it leaves — 32 percent today.</li>
</ul>
<section id="data-and-code" class="level3">
<h3 class="anchored" data-anchor-id="data-and-code">Data and code</h3>
<p>All data are public: Tether’s and Circle’s attestations (118 reports), the LCR disclosures of the twenty-one reporting bank holding companies, FDIC call reports, the Federal Reserve’s H.8 and H.4.1 releases, FRED, the Treasury’s Monthly Statement of the Public Debt and DefiLlama. The empirical specifications were fixed before estimation. The analysis plans and the model and estimation code are available on request at <a href="mailto:hyunhak.kim@kookmin.ac.kr">hyunhak.kim@kookmin.ac.kr</a>.</p>
</section>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<p>Ahmed, R. and Aldasoro, I. (2026). Stablecoins and safe asset prices. BIS Working Paper 1270.</p>
<p>Bech, M. L. and Keister, T. (2017). Liquidity regulation and the implementation of monetary policy. <em>Journal of Monetary Economics</em>, 92, 64–77.</p>
<p>Hofmann, B., Kaldorf, M. and Rottner, M. (2026). The macroeconomics of stablecoins. BIS Working Paper 1363.</p>
<p>Lee, M. J. and Tou, D. (2026). Stablecoin disintermediation. Federal Reserve Bank of New York Staff Report 1185.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/khdouble\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© Hyun Hak Kim · Department of Economics, Kookmin University</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>