<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-29">
<meta name="description" content="Holding the workplace fixed, a municipality whose standardized rent is 10 percent higher is chosen about 10 percent less often as a residence by young Korean wage workers. This note sets out where that gradient comes from — persistent differences between municipalities, confined to the capital region — and what a handful of cities at the capital boundary do to the sharpest contrast.">

<title>Cheaper but Farther – Hyun Hak Kim</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-0b873dab1a9bb082c1df6b2c2700682a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-d7d8c43c9bbf52025258093b17e489d4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-0b873dab1a9bb082c1df6b2c2700682a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,400;8..60,600;8..60,700&amp;display=swap">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Cheaper but Farther – Hyun Hak Kim">
<meta property="og:description" content="Holding the workplace fixed, a municipality whose standardized rent is 10 percent higher is chosen about 10 percent less often as a residence by young Korean wage workers. This note sets out where that gradient comes from — persistent differences between municipalities, confined to the capital region — and what a handful of cities at the capital boundary do to the sharpest contrast.">
<meta property="og:image" content="https://khdouble.github.io/posts/2026-09-cheaper-but-farther-en/figures/figure1_regions_rent_map.png">
<meta property="og:site_name" content="Hyun Hak Kim">
<meta property="og:image:height" content="904">
<meta property="og:image:width" content="2180">
<meta property="og:image:alt" content="Map of Korean municipalities shaded by standardized rent, with the capital region outlined">
</head>

<body class="nav-sidebar docked article quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      Hyun Hak Kim
      </li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Hyun Hak Kim</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="../../files/cv-hyunhak-kim.pdf" title="Curriculum Vitae" class="quarto-navigation-tool px-1" aria-label="Curriculum Vitae"><i class="bi bi-file-earmark-text"></i></a>
    <a href="mailto:hyunhak.kim@kookmin.ac.kr" title="Email" class="quarto-navigation-tool px-1" aria-label="Email"><i class="bi bi-envelope"></i></a>
    <a href="https://www.linkedin.com/in/khdouble/" title="LinkedIn" class="quarto-navigation-tool px-1" aria-label="LinkedIn"><i class="bi bi-linkedin"></i></a>
    <a href="https://github.com/khdouble" title="GitHub" class="quarto-navigation-tool px-1" aria-label="GitHub"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Research</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../blog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Blog</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../links.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Links</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#where-do-young-wage-workers-live-given-where-they-work" id="toc-where-do-young-wage-workers-live-given-where-they-work" class="nav-link active" data-scroll-target="#where-do-young-wage-workers-live-given-where-they-work">Where do young wage workers live, given where they work?</a></li>
  <li><a href="#a-residence-choice-with-the-workplace-held-fixed" id="toc-a-residence-choice-with-the-workplace-held-fixed" class="nav-link" data-scroll-target="#a-residence-choice-with-the-workplace-held-fixed">1. A residence choice with the workplace held fixed</a></li>
  <li><a href="#rent-measured-on-a-common-basis-for-every-municipality" id="toc-rent-measured-on-a-common-basis-for-every-municipality" class="nav-link" data-scroll-target="#rent-measured-on-a-common-basis-for-every-municipality">2. Rent measured on a common basis, for every municipality</a></li>
  <li><a href="#a-gradient-of-1.15-that-does-not-depend-on-the-choice-set-the-round-or-the-inference" id="toc-a-gradient-of-1.15-that-does-not-depend-on-the-choice-set-the-round-or-the-inference" class="nav-link" data-scroll-target="#a-gradient-of-1.15-that-does-not-depend-on-the-choice-set-the-round-or-the-inference">3. A gradient of −1.15 that does not depend on the choice set, the round, or the inference</a></li>
  <li><a href="#the-gradient-lives-between-municipalities-not-within-them" id="toc-the-gradient-lives-between-municipalities-not-within-them" class="nav-link" data-scroll-target="#the-gradient-lives-between-municipalities-not-within-them">4. The gradient lives between municipalities, not within them</a></li>
  <li><a href="#it-is-a-capital-region-phenomenon" id="toc-it-is-a-capital-region-phenomenon" class="nav-link" data-scroll-target="#it-is-a-capital-region-phenomenon">5. It is a capital-region phenomenon</a></li>
  <li><a href="#the-boundary-result-and-the-five-cities-behind-it" id="toc-the-boundary-result-and-the-five-cities-behind-it" class="nav-link" data-scroll-target="#the-boundary-result-and-the-five-cities-behind-it">6. The boundary result, and the five cities behind it</a></li>
  <li><a href="#cheaper-but-farther-workers-at-expensive-workplace-centres" id="toc-cheaper-but-farther-workers-at-expensive-workplace-centres" class="nav-link" data-scroll-target="#cheaper-but-farther-workers-at-expensive-workplace-centres">7. Cheaper but farther: workers at expensive workplace centres</a></li>
  <li><a href="#what-the-gradient-is-not" id="toc-what-the-gradient-is-not" class="nav-link" data-scroll-target="#what-the-gradient-is-not">8. What the gradient is not</a></li>
  <li><a href="#the-boundary-of-what-the-current-evidence-supports" id="toc-the-boundary-of-what-the-current-evidence-supports" class="nav-link" data-scroll-target="#the-boundary-of-what-the-current-evidence-supports">9. The boundary of what the current evidence supports</a></li>
  <li><a href="#what-would-move-this-forward" id="toc-what-would-move-this-forward" class="nav-link" data-scroll-target="#what-would-move-this-forward">10. What would move this forward</a></li>
  <li><a href="#working-paper" id="toc-working-paper" class="nav-link" data-scroll-target="#working-paper">Working paper</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Cheaper but Farther</h1>
<p class="subtitle lead">Where young Korean wage workers live given where they work, where the rent gradient in that choice comes from, and why it is a feature of the capital region rather than of the country</p>
  <div class="quarto-categories">
    <div class="quarto-category">English</div>
    <div class="quarto-category">Housing</div>
    <div class="quarto-category">Regional Economics</div>
  </div>
  </div>

<div>
  <div class="description">
    Holding the workplace fixed, a municipality whose standardized rent is 10 percent higher is chosen about 10 percent less often as a residence by young Korean wage workers. This note sets out where that gradient comes from — persistent differences between municipalities, confined to the capital region — and what a handful of cities at the capital boundary do to the sharpest contrast.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 29, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>한국어판</strong> — <a href="../2026-09-cheaper-but-farther-ko/">비싼 직장, 먼 집</a></p>
<p>Worker data are the 2021H2–2024H2 rounds of the Regional Employment Survey of Statistics Korea, accessed through its Microdata Integrated Service; each respondent’s residence and workplace are recorded at the municipality (<em>si-gun-gu</em>) level. Rent is a standardized index built from 5,159,595 monthly-rent lease contracts reported to the Real Transaction Management System between 2017H1 and 2024H2.</p>
</div>
</div>
</div>
<section id="where-do-young-wage-workers-live-given-where-they-work" class="level2">
<h2 class="anchored" data-anchor-id="where-do-young-wage-workers-live-given-where-they-work">Where do young wage workers live, given where they work?</h2>
<p>Where a young worker lives is a joint outcome of housing costs, access to jobs, amenities and housing supply, and no single coefficient in a residential-choice model separates these forces. Rent is an equilibrium price that capitalizes access and amenities (Roback, 1982; Glaeser and Gottlieb, 2009), so a negative coefficient on the rent of a residence may reflect cost avoidance, sorting on unmeasured quality, or the location of jobs — and housing costs in expensive labour markets may themselves limit who gets to work there (Hsieh and Moretti, 2019; Ganong and Shoag, 2017). Korea makes the question sharp. The capital region — Seoul, Incheon and Gyeonggi — holds 57.8 percent of the workplaces of young wage workers, and its rent levels sit above the rest of the country in a stable order.</p>
<p>This study does not try to separate all of these forces. It asks a narrower question that the available data can answer: among employed wage workers aged 19–34 who hold a job in a given municipality, how is the standardized rent of a municipality related to whether they choose it as a residence, once the workplace, commuting distance and measured amenities are held fixed — and where in the country, and for whom, does that relation hold? Three answers follow. The conditional rent gradient is negative and stable across choice sets, survey rounds and inference methods. It arises from persistent differences in rent levels between municipalities, not from changes in a municipality’s own rent. And it is confined to capital-region residences, where workers at the most expensive workplace centres combine a steeper gradient with residence in cheaper, more distant municipalities.</p>
<section id="headline-figures" class="level3">
<h3 class="anchored" data-anchor-id="headline-figures">Headline figures</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Estimation sample</td>
<td style="text-align: right;">224,862 wage workers aged 19–34, seven half-years</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residence alternatives in each choice</td>
<td style="text-align: right;">207–212 municipalities</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lease contracts behind the rent index</td>
<td style="text-align: right;">5,159,595</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log-rent coefficient, full choice set</td>
<td style="text-align: right;">−1.153 (0.263)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Change in relative odds of a residence with 10 percent higher rent</td>
<td style="text-align: right;">−10.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Within-municipality vs.&nbsp;between-municipality coefficient</td>
<td style="text-align: right;">0.080 vs.&nbsp;−1.254</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Between slope, capital-region minus noncapital residences</td>
<td style="text-align: right;">−2.166; −1.903 without the five commuter cities</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rent slope at high-rent workplace centres vs.&nbsp;other workplaces</td>
<td style="text-align: right;">−1.739 vs.&nbsp;−0.238</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Workers at high-rent centres living in a municipality cheaper than the workplace</td>
<td style="text-align: right;">48.5% vs.&nbsp;11.2% elsewhere</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="a-residence-choice-with-the-workplace-held-fixed" class="level2">
<h2 class="anchored" data-anchor-id="a-residence-choice-with-the-workplace-held-fixed">1. A residence choice with the workplace held fixed</h2>
<p>The unit of analysis is the residence municipality chosen by a wage worker whose workplace municipality is observed. For each worker the alternatives are every municipality in the country whose lease records support a measured rent in that half-year — 207 to 212 of them — and the choice among them is modelled as a conditional logit (McFadden, 1974). A worker of type <span class="math inline">\(g\)</span> (sex, education and age band) employed in municipality <span class="math inline">\(j\)</span> in half-year <span class="math inline">\(t\)</span> obtains from residence <span class="math inline">\(r\)</span> the systematic utility</p>
<p><span class="math display">\[V_{grjt}=\lambda_{gtj}+\beta_H h_{rt}+\beta_D\log(1+d_{rj})+\beta_S\mathbf{1}\{r=j\}+\beta_P\mathbf{1}\{p(r)=p(j)\}+\boldsymbol{\gamma}'\mathbf{A}_{rt}+\rho_{p(r)},\]</span></p>
<p>where <span class="math inline">\(h_{rt}\)</span> is log standardized rent, <span class="math inline">\(d_{rj}\)</span> the centroid distance to the workplace, <span class="math inline">\(\mathbf{A}_{rt}\)</span> four amenity indices, and <span class="math inline">\(\rho_{p(r)}\)</span> a residence-province effect. The choice-group effect <span class="math inline">\(\lambda_{gtj}\)</span> absorbs everything common to the residences available to that worker.</p>
<p>Conditioning on the workplace is what makes the coefficient a residential comparison. Expected wages, job openings and the industry mix of the workplace are common to all alternatives and drop out of the likelihood; what remains is a comparison of residences by rent, amenities and distance to a fixed job. The design is not a joint model of employment and workplace choice, and it does not treat the workplace as exogenous — workers may choose jobs and homes together. Nor does it observe moves: the survey is a sequence of repeated cross-sections, so what is described is where employed young workers live in each half-year, not how individuals relocate. And <span class="math inline">\(\beta_H\)</span> is a conditional gradient, not a demand elasticity, because rent is an equilibrium price that also carries unobserved quality, productivity and supply.</p>
<p>Two features of the design matter later. The full choice set makes sampling of alternatives unnecessary; sampled choice sets with the McFadden (1978) correction serve only as a check. And because every group faces all rent-eligible residences, the 224,862 workers generate 4,498,851 choice-set rows in 21,379 groups — which, when residence attributes do not vary by worker type, collapse exactly to 335,839 rows in 1,596 half-year-by-workplace groups without changing the likelihood. Inference clusters two ways, by residence and by workplace geography (Cameron, Gelbach and Miller, 2011), and the main estimands also receive wild-score intervals from 999 Rademacher draws over residence blocks and over workplace blocks (Kline and Santos, 2012), because the number of geographic clusters is limited.</p>
<p>The geography the model has to explain is compact. In the estimation sample 51.8 percent of workers live and work in the same municipality and 85.2 percent in the same province; the mean centroid distance between residence and workplace is 8.6 km and its 90th percentile 24.5 km. Commuting across the capital-region boundary is rare in both directions — capital residents with noncapital workplaces carry 0.44 percent of the survey weight, and noncapital residents with capital workplaces 0.35 percent — a fact that becomes decisive in Section 6.</p>
</section>
<section id="rent-measured-on-a-common-basis-for-every-municipality" class="level2">
<h2 class="anchored" data-anchor-id="rent-measured-on-a-common-basis-for-every-municipality">2. Rent measured on a common basis, for every municipality</h2>
<p>Raw medians of reported rents would mix local price levels with differences in unit size, housing type, building age, floor and contract month. The rent measure therefore comes from a contract-level hedonic regression estimated on all 5,159,595 eligible monthly-rent contracts for units of at most 60 m² signed between 2017H1 and 2024H2. Each contract’s monthly-equivalent cost converts the deposit at the three-year Treasury yield,</p>
<p><span class="math display">\[MEC_{hm}=R_{hm}+\frac{i_m}{12}\,D_{hm},\]</span></p>
<p>expressed at 2024 prices. Log cost is regressed on quadratics in floor area, building age and floor, on housing-type and month indicators, and on a fixed effect for each geographic unit and half-year. The standardized rent evaluates the fitted price at 40 m², ten years of age and the third floor, with housing types weighted by fixed national contract shares, so that shifts in the composition of reported leases cannot move the index. Pure deposit leases (<em>jeonse</em>) carry no monthly rent and are excluded from the baseline; a deposit-inclusive variant that admits them serves as a sensitivity measure.</p>
<p>A municipality enters the choice set in a half-year only if it records at least 20 eligible contracts, and nothing is imputed for sparse cells. The threshold mostly removes rural counties, where the lease-reporting obligation introduced in June 2021 does not apply: of the 130 municipality-half-year cells below it, 128 lie in counties outside the mandatory reporting area. The rent-eligible cells contain 3,102,349 contracts. Across comparable cells the standardized index has a correlation of 0.849 with the raw median, which supports it as a ranking of local rent levels without turning an equilibrium rent into an exogenous price.</p>
<table class="caption-top table">
<caption>Standardized rent of a 40 m² unit, in 10,000 won per month at 2024 prices, across rent-eligible municipality-half-year cells, 2021H2–2024H2. Each cell is weighted equally. The three capital-region groups do not merely sit above the rest of the country; their ranges barely overlap with it, which is what allows the between-municipality decomposition of Section 4 to find something.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Residence region</th>
<th style="text-align: right;">Municipality-half-year cells</th>
<th style="text-align: right;">5th percentile</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">95th percentile</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Seoul</td>
<td style="text-align: right;">175</td>
<td style="text-align: right;">50.2</td>
<td style="text-align: right;">63.8</td>
<td style="text-align: right;">87.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gyeonggi</td>
<td style="text-align: right;">217</td>
<td style="text-align: right;">32.8</td>
<td style="text-align: right;">45.9</td>
<td style="text-align: right;">64.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Incheon</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">34.0</td>
<td style="text-align: right;">42.4</td>
<td style="text-align: right;">56.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Outside the capital region</td>
<td style="text-align: right;">1,011</td>
<td style="text-align: right;">23.0</td>
<td style="text-align: right;">35.5</td>
<td style="text-align: right;">44.6</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure1_regions_rent_map.png" class="img-fluid figure-img"></p>
<figcaption>Figure 1. Regions, commuter cities and standardized rent. Panel (a) outlines the capital region in red and numbers the ten noncapital municipalities that carry the largest survey weight among noncapital residents employed in the capital region; the first five are the commuter cities of Section 6. Hatched municipalities are rent-eligible in fewer than seven of the seven half-years. Panel (b) shades each municipality by the mean of its standardized 40 m² rent over its rent-eligible half-years, in 10,000 won per month at 2024 prices, with class breaks at the sextiles.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure2_rent_index.png" class="img-fluid figure-img"></p>
<figcaption>Figure 2. Construction and support of standardized rent. Panel (a) plots the median across rent-eligible municipalities of the hedonic 40 m² monthly-equivalent rent, by region and half-year. Panel (b) counts municipality-half-year cells by their number of eligible contracts; cells with no contract are shown at one. The 20-contract threshold falls in the thin left tail, and the regional order in panel (a) is the same in every half-year.</figcaption>
</figure>
</div>
</section>
<section id="a-gradient-of-1.15-that-does-not-depend-on-the-choice-set-the-round-or-the-inference" class="level2">
<h2 class="anchored" data-anchor-id="a-gradient-of-1.15-that-does-not-depend-on-the-choice-set-the-round-or-the-inference">3. A gradient of −1.15 that does not depend on the choice set, the round, or the inference</h2>
<table class="caption-top table">
<caption>Workplace-conditioned conditional logit over every rent-eligible residence municipality, with the four amenity indices and residence-province fixed effects. Standard errors clustered two-way by residence and workplace geography. 224,862 persons, 21,379 choice groups, 4,498,851 choice-set rows.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">(1) Pooled</th>
<th style="text-align: right;">(2) Capital-region interaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Log rent</td>
<td style="text-align: right;">−1.153 (0.263)</td>
<td style="text-align: right;">0.534 (0.329)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log rent × capital-region residence</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">−1.979 (0.428)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Log (1 + distance)</td>
<td style="text-align: right;">−1.919 (0.057)</td>
<td style="text-align: right;">−1.926 (0.057)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Same municipality</td>
<td style="text-align: right;">−2.431 (0.190)</td>
<td style="text-align: right;">−2.445 (0.190)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Same province</td>
<td style="text-align: right;">0.642 (0.087)</td>
<td style="text-align: right;">0.633 (0.087)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Implied slope, capital-region residences</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">−1.446 (0.275)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Implied slope, noncapital residences</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.534 (0.329), p = 0.105</td>
</tr>
</tbody>
</table>
<p>Because the regressor is log rent, a coefficient of −1.153 means that a residence whose standardized rent is 10 percent higher has a 10.4 percent lower relative odds of being chosen, holding the workplace and the other measured attributes fixed. The commuting terms confirm that spatial friction shapes the residence choice of a worker with a given job, which is what the workplace-conditioned design requires; they and the amenity indices are controls and are not interpreted individually, because the same-municipality indicator is defined jointly with a zero centroid distance.</p>
<p>The benchmark is not an artefact of the choice set or of any single survey round. Across five random seeds, sampled choice sets with 12 zero-flow alternatives per stratum and the McFadden offset give a mean coefficient of −1.155, which is 0.17 percent away from the full-choice value; omitting the offset moves the estimate to −1.049, so the correction matters even though the full choice set makes it unnecessary. Re-estimating the full-choice model with one half-year omitted yields coefficients between −1.201 and −1.120. Predicted municipality residence shares track observed shares with a Spearman correlation of 0.978 in sample and between 0.975 and 0.979 for the omitted half-years.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure3_full_choice_validation.png" class="img-fluid figure-img"></p>
<figcaption>Figure 3. Full-choice stability and predictive validation. Panel (a) plots five random seeds for each number of sampled zero-flow alternatives, with the McFadden offset, against the full-choice estimate and its two-way clustered 95 percent interval; the hollow marker omits the offset. Panel (b) re-estimates the full-choice model dropping one half-year at a time. Panel (c) plots predicted against observed municipality residence shares on log scales.</figcaption>
</figure>
</div>
<p>The inference method does not matter either. The two-way clustered 95 percent interval for the pooled coefficient is [−1.668, −0.638]; the wild-score intervals over residence blocks and workplace blocks are [−1.513, −0.756] and [−1.569, −0.729]. For the capital-minus-noncapital contrast introduced in column (2) — −1.979 in this pooled specification — the corresponding intervals are [−2.819, −1.140], [−2.654, −1.293] and [−2.703, −1.187]. Section 5 takes that contrast up with persistent rent levels and shows what it does and does not depend on.</p>
</section>
<section id="the-gradient-lives-between-municipalities-not-within-them" class="level2">
<h2 class="anchored" data-anchor-id="the-gradient-lives-between-municipalities-not-within-them">4. The gradient lives between municipalities, not within them</h2>
<p>A pooled gradient combines two kinds of variation: changes in a municipality’s rent over time, and persistent differences in rent across municipalities. The two need not carry the same information. Long-run level differences reflect the durable structure of amenities and access, whereas half-year deviations mix local shocks with the composition of reported leases. A Mundlak decomposition separates them by replacing <span class="math inline">\(\beta_H h_{rt}\)</span> with</p>
<p><span class="math display">\[\beta_W\,(h_{rt}-\bar h_r)+\beta_B\,\bar h_r,\]</span></p>
<p>where <span class="math inline">\(\bar h_r\)</span> is the municipality’s mean log rent over the seven half-years, with the same split applied to the amenity indices and half-year-by-workplace effects in place of the choice-group effects.</p>
<table class="caption-top table">
<caption>The first three rows are the pooled Mundlak model; the last two replace the province effects and the between components with a residence-municipality effect, and then add municipality-specific linear trends. Wild-score intervals are not available for the sparse fixed-effect models.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate (s.e.)</th>
<th style="text-align: right;">p-value</th>
<th style="text-align: right;">Residence-block wild 95%</th>
<th style="text-align: right;">Workplace-block wild 95%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Within-municipality rent</td>
<td style="text-align: right;">0.080 (0.073)</td>
<td style="text-align: right;">0.273</td>
<td style="text-align: right;">[−0.037, 0.212]</td>
<td style="text-align: right;">[−0.067, 0.226]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Between-municipality rent</td>
<td style="text-align: right;">−1.254 (0.281)</td>
<td style="text-align: right;">&lt; 0.001</td>
<td style="text-align: right;">[−1.646, −0.855]</td>
<td style="text-align: right;">[−1.690, −0.813]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Within minus between</td>
<td style="text-align: right;">1.334 (0.295)</td>
<td style="text-align: right;">&lt; 0.001</td>
<td style="text-align: right;">[0.901, 1.757]</td>
<td style="text-align: right;">[0.868, 1.794]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Within rent, municipality fixed effects</td>
<td style="text-align: right;">0.103 (0.081)</td>
<td style="text-align: right;">0.203</td>
<td style="text-align: right;">n.a.</td>
<td style="text-align: right;">n.a.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Within rent, municipality fixed effects and trends</td>
<td style="text-align: right;">0.041 (0.062)</td>
<td style="text-align: right;">0.508</td>
<td style="text-align: right;">n.a.</td>
<td style="text-align: right;">n.a.</td>
</tr>
</tbody>
</table>
<p>A municipality whose seven-half-year average rent is 10 percent higher has an 11.3 percent lower relative odds of being chosen, whereas a 10 percent deviation of a municipality’s rent from its own average is associated with no comparable change. Every interval for the between coefficient excludes zero, every interval for the within coefficient includes it, and both intervals for their difference exclude it. The two stricter specifications reach the same conclusion.</p>
<p>The pooled gradient of Section 3 is therefore spatial sorting across municipalities, not a response to short-run rent changes. The paper is careful about what the within coefficient does not show. Seven half-years provide little within-municipality variation, and time-varying local shocks can move rent and residential choice together, so a within coefficient indistinguishable from zero is best read as uninformative in this design rather than as evidence that rent changes do not matter.</p>
<p>Timing checks say the same thing from the other side. The capital-workplace contrast of Section 6 is −5.512 with region-by-half-year effects, −5.469 when the sample starts in 2022H1, and −4.576 with rent lagged one half-year — but only 0.344 (p = 0.642) when current rent is replaced by its year-on-year change. Lagged and differenced rents are not instruments; they show that the pattern rides on persistent rent levels rather than on recent rent movements.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure4_rent_gradient_origin.png" class="img-fluid figure-img"></p>
<figcaption>Figure 4. Spatial origin of the rent gradient. Panel (a) reports log-rent coefficients from the pooled Mundlak model and from the municipality fixed-effect models; the thin line is the residence-block wild-score interval, which the fixed-effect models cannot provide. Panels (b) and (c) report between-municipality slopes for capital-region and noncapital residences, and their contrast, before and after removing the five and then the ten commuter cities from every choice set. Intervals are two-way clustered 95 percent intervals.</figcaption>
</figure>
</div>
</section>
<section id="it-is-a-capital-region-phenomenon" class="level2">
<h2 class="anchored" data-anchor-id="it-is-a-capital-region-phenomenon">5. It is a capital-region phenomenon</h2>
<p>Where is the between-municipality gradient located? Letting the between slope differ between capital-region and noncapital residences, for all workers, gives −1.527 for capital-region residences and 0.639 (p = 0.112) for noncapital residences — a contrast of −2.166 (p &lt; 0.001). Across noncapital residences, persistent rent differences are not detectably related to residential choice. The between-municipality gradient is a capital-region phenomenon.</p>
<table class="caption-top table">
<caption>Mundlak between-municipality slopes for all workplaces. The excluded cities are the noncapital residences that carry the largest weight among noncapital residents employed in the capital region — Cheonan, Asan, Wonju, Cheongju and Chuncheon, and then Sejong, two districts of Daejeon, Eumseong and Jincheon — removed from every choice set.</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Between slope</th>
<th style="text-align: right;">All residences</th>
<th style="text-align: right;">Excluding five commuter cities</th>
<th style="text-align: right;">Excluding ten</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Capital-region residences</td>
<td style="text-align: right;">−1.527 (0.289)</td>
<td style="text-align: right;">−1.520 (0.294)</td>
<td style="text-align: right;">−1.518 (0.296)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Noncapital residences</td>
<td style="text-align: right;">0.639 (0.402)</td>
<td style="text-align: right;">0.384 (0.408)</td>
<td style="text-align: right;">0.349 (0.417)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Capital minus noncapital</td>
<td style="text-align: right;">−2.166 (0.496)</td>
<td style="text-align: right;">−1.903 (0.507)</td>
<td style="text-align: right;">−1.867 (0.519)</td>
</tr>
</tbody>
</table>
<p>This contrast does not depend on the few noncapital cities that dominate cross-boundary commuting. Removing the five largest of them leaves the capital slope at −1.520 and the contrast at −1.903; removing ten leaves it at −1.867. The pooled interaction of Section 3 behaves the same way, with a contrast of −1.760 after the five-city exclusion and −1.736 after the ten-city exclusion.</p>
<p>Nor is the gradient Seoul alone. Letting the pooled slope differ by province gives −1.977 for Seoul residences, −1.240 for Gyeonggi and −0.626 (p = 0.259) for Incheon, against 0.486 (p = 0.147) for noncapital residences; removing each province from every choice set in turn leaves the capital-minus-noncapital difference at −1.539 without Seoul, −2.098 without Incheon and −2.210 without Gyeonggi.</p>
<p>Common support is the more serious limit, since capital-region municipalities occupy the upper rent range. Keeping in each half-year only the alternatives whose log rent lies within the 5th–95th percentile range shared by the two groups gives a contrast of −2.564 (p = 0.027), with component slopes of −1.972 (p = 0.069) and 0.593 (p = 0.329) — on a sample that retains only 19.7 to 24.2 percent of capital-region residence cells per half-year. The contrast keeps its sign on common support, but a result resting on a fifth of the capital region’s cells does not show that it holds across the full rent distribution, and the paper says so.</p>
</section>
<section id="the-boundary-result-and-the-five-cities-behind-it" class="level2">
<h2 class="anchored" data-anchor-id="the-boundary-result-and-the-five-cities-behind-it">6. The boundary result, and the five cities behind it</h2>
<p>Narrowing the comparison to workers employed in the capital region produces a far larger contrast — and the paper’s most instructive diagnosis. In the residence-by-workplace market model, the between slope among these workers is −1.515 for capital-region residences and 4.016 for noncapital residences, so the contrast is −5.531 (1.206; p &lt; 0.001), with a residence-block wild-score interval of [−8.054, −3.073]. The difference-in-differences against noncapital workplaces is −4.564. Read on its own, this would suggest a far sharper ordering by rent among capital-region workers than Section 5 shows for all workers.</p>
<p>That reading does not survive inspection of the cell that produces it. Noncapital residents employed in the capital region carry only 0.35 percent of the survey weight, and five municipalities account for 71.3 percent of that cell: Cheonan (33.4 percent), Asan (18.5), Wonju (9.2), Cheongju (5.2) and Chuncheon (5.0); the ten largest account for 85.3 percent.</p>
<table class="caption-top table">
<caption>Between-municipality slopes from the residence-by-workplace market model, with the commuter cities removed from every choice set. Removing Cheonan alone already reduces the contrast to −3.605.</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Capital-region workplaces</th>
<th style="text-align: right;">All residences</th>
<th style="text-align: right;">Excluding five</th>
<th style="text-align: right;">Excluding ten</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Capital-region residences</td>
<td style="text-align: right;">−1.515 (0.282)</td>
<td style="text-align: right;">−1.505 (0.286)</td>
<td style="text-align: right;">−1.504 (0.289)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Noncapital residences</td>
<td style="text-align: right;">4.016 (1.187)</td>
<td style="text-align: right;">0.537 (0.782)</td>
<td style="text-align: right;">0.684 (1.024)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Capital minus noncapital</td>
<td style="text-align: right;">−5.531 (1.206)</td>
<td style="text-align: right;">−2.042 (0.850)</td>
<td style="text-align: right;">−2.188 (1.045)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Difference-in-differences vs.&nbsp;noncapital workplaces</td>
<td style="text-align: right;">−4.564 (1.234)</td>
<td style="text-align: right;">−1.264 (0.953)</td>
<td style="text-align: right;">−1.445 (1.147)</td>
</tr>
</tbody>
</table>
<p>Removing the five cities from every choice set leaves the capital-region slope at −1.505 but reduces the noncapital slope to 0.537 (p = 0.492), whose wild-score intervals now include zero. The contrast falls to −2.042 (p = 0.016), still excluding zero, and the difference-in-differences to −1.264 (p = 0.185), no longer distinguishable from it.</p>
<p>The five municipalities are not commuter towns oriented toward Seoul. They are large noncapital labour markets close to the capital boundary. Among noncapital rent-eligible municipalities their youth job-stock percentiles run from the 85th to the 100th; between 73 and 92 percent of their resident wage workers are employed within their own city, and only 0.9 to 8.0 percent commute to the capital region. The nearest capital-region municipality lies 23 to 50 km away, and their standardized rent ranks relatively high among noncapital municipalities, at the 59th to 87th percentile. The largest destinations of their capital-region commuters are municipalities just across the boundary in outer Gyeonggi — from Cheonan and Asan to Pyeongtaek, Anseong and Hwaseong; from Wonju to Yeoju and Icheon; from Cheongju to Icheon; from Chuncheon to Gapyeong — followed by the Gangnam and Songpa districts of Seoul. Among these commuters, 40 percent travel 40 km or less, compared with 12 percent among the remaining noncapital residents employed in the capital region, whose mean commuting distance is 121 km.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure5_commuter_cities.png" class="img-fluid figure-img"></p>
<figcaption>Figure 5. The five commuter cities at the capital-region boundary. Panel (a) shades the five noncapital municipalities that carry the largest survey weight among noncapital residents employed in the capital region and reports, for each, the share of its resident wage workers employed in the city itself and in the capital region, the distance to the nearest capital-region municipality, and the city’s rent percentile among noncapital municipalities. Panel (b) draws an arrow from each city to the three largest destinations of its capital-region commuters, with width proportional to the destination’s share; squares mark the cities ranked sixth to tenth.</figcaption>
</figure>
</div>
<p>The positive noncapital slope in the capital-workplace market therefore does not show capital-workplace commuters avoiding high rent within the capital region. It reflects commuting across the administrative capital boundary between adjacent labour markets, in which a large and relatively expensive noncapital city is chosen as a residence over closer and cheaper alternatives. It should not be read as evidence that these commuters prefer expensive housing, and the survey counts — 427 commuters for the five cities combined — are too small for more than an aggregate description.</p>
<p>Sections 5 and 6 thus say two different things, and the paper keeps them apart. The between-municipality gradient is confined to capital-region residences, and that concentration survives the removal of the commuter cities. The additional contrast among capital-region workers is a boundary result that depends on a handful of adjacent cities; it is reported only together with the exclusions. Two further contrasts are reported with the same weight and carry nothing: for workers employed outside the capital region the capital-minus-noncapital contrast is −0.968 (p = 0.107), significant under workplace-block but not residence-block inference, and the within-municipality contrast for capital-region workplaces is imprecise and unstable across exclusions.</p>
</section>
<section id="cheaper-but-farther-workers-at-expensive-workplace-centres" class="level2">
<h2 class="anchored" data-anchor-id="cheaper-but-farther-workers-at-expensive-workplace-centres">7. Cheaper but farther: workers at expensive workplace centres</h2>
<p>If the between-municipality gradient reflects sorting around expensive workplaces, workers attached to the most expensive workplaces should show it most clearly, together with the commuting that such sorting requires. A workplace municipality is a high-rent centre in a half-year if its standardized rent lies in the top quartile of workplaces; of the 401 centre-half-year cells, 83.0 percent are capital-region municipalities, and 56.3 percent of the workers employed at such centres have workplaces in Seoul.</p>
<table class="caption-top table">
<caption>Rent and distance slopes allowed to differ for workplaces in the top quartile of standardized rent or of youth job openings within each half-year.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">High-rent centres</th>
<th style="text-align: right;">High-opening centres</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rent slope, centre workplaces</td>
<td style="text-align: right;">−1.739 (0.265)</td>
<td style="text-align: right;">−1.161 (0.306)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rent slope, other workplaces</td>
<td style="text-align: right;">−0.238 (0.309)</td>
<td style="text-align: right;">−1.236 (0.242)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rent-slope difference</td>
<td style="text-align: right;">−1.501 (0.357)</td>
<td style="text-align: right;">0.075 (0.279)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Distance-slope difference</td>
<td style="text-align: right;">−0.047 (0.055)</td>
<td style="text-align: right;">0.132 (0.043)</td>
</tr>
</tbody>
</table>
<p>Workers employed at high-rent centres have a rent slope of −1.739, against −0.238 (p = 0.441) for workers at other workplaces — a difference of −1.501 — while their distance slope differs by only −0.047 (p = 0.395). The observed flows behind this contrast are what the title describes.</p>
<table class="caption-top table">
<caption>Survey-weighted flows of the estimation sample. A residence is cheaper when its standardized log rent is below the workplace’s.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Observed commuting</th>
<th style="text-align: right;">Centre workplaces</th>
<th style="text-align: right;">Other workplaces</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean commuting distance (km)</td>
<td style="text-align: right;">10.09</td>
<td style="text-align: right;">7.07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Live in a municipality cheaper than the workplace (%)</td>
<td style="text-align: right;">48.5</td>
<td style="text-align: right;">11.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cheaper and within 30 km (%)</td>
<td style="text-align: right;">43.4</td>
<td style="text-align: right;">9.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cheaper and beyond 30 km (%)</td>
<td style="text-align: right;">5.12</td>
<td style="text-align: right;">1.32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Live in the workplace municipality (%)</td>
<td style="text-align: right;">37.5</td>
<td style="text-align: right;">66.2</td>
</tr>
</tbody>
</table>
<p>High-opening centres — the top quartile of youth job openings — show a different pattern, reported with the same weight. Their rent-slope difference is 0.075 (p = 0.788), with both slopes negative and similar, and their distance slope is 0.132 (p = 0.002) <em>less</em> negative than elsewhere. Density of job openings by itself does not produce the pattern; a high rent level at the workplace does.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure6_commuting_tradeoffs.png" class="img-fluid figure-img"></p>
<figcaption>Figure 6. Commuting trade-offs and employment-selection sensitivity. Panel (a) plots rent slopes for centre and other workplaces under the two centre definitions. Panel (b) describes the observed flows for the rent-centre definition. Panels (c) and (d) re-estimate the between-municipality slope and the capital-workplace contrast after reweighting wage workers toward all persons aged 19–34 on observed characteristics (Section 8); the overlap weight was not estimated for the market-structure model.</figcaption>
</figure>
</div>
<p>Workers tied to an expensive workplace centre therefore live cheaper but farther: they show a steeper rent gradient, more often live in a municipality whose rent is below that of their workplace, and commute longer than workers at other workplaces. Because high-rent centres lie mostly in the capital region, this is the worker-level counterpart of the capital-region concentration in Section 5. The pattern is descriptive. Centre status, residential rent and commuting distance are jointly determined by metropolitan structure, and the paper does not present it as a causal mediation.</p>
</section>
<section id="what-the-gradient-is-not" class="level2">
<h2 class="anchored" data-anchor-id="what-the-gradient-is-not">8. What the gradient is not</h2>
<p>Three explanations were tested and are not supported. The first is that expensive municipalities are chosen because they give access to more jobs. Adding a distance-decayed job-access index to the Mundlak model as within and between terms leaves the between rent slope between −1.240 and −1.251, while the between component of access is −0.011 (p = 0.947) for youth openings within 30 km, −0.029 (p = 0.873) within 60 km, and −0.035 (p = 0.851) for the employed-youth stock within 30 km; with access held constant, the capital-workplace contrast is −5.625. The second is that workers with lower earning capacity are more sensitive to rent: slopes by quartile of Mincer-predicted wages run from −1.071 to −1.304, and the lowest quartile differs from the highest by −0.190 (p = 0.435). The third is that static small-unit housing supply shapes the gradient: the between slope is −1.183 where the supply constraint is low and −1.260 where it is high, a difference of −0.077 (p = 0.829). Municipal aggregates and a single 2024 supply cross-section give these tests limited power against subtler versions of the mechanisms, and the paper says so.</p>
<p>Differences by age, sex and education were predeclared as uncertain in sign and are reported regardless of significance. With one interaction at a time the pooled slope is negative and precisely estimated in every group, between −1.069 and −1.291; the differences are −0.107 (p = 0.226) for workers aged 19–29 relative to 30–34, −0.168 (p = 0.086) for women relative to men, and 0.197 (p = 0.201) for four-year college graduates, and jointly they give a Wald statistic of 3.192 on 3 degrees of freedom (p = 0.363).</p>
<p>The rent measure does not produce the results. Including <em>jeonse</em> leases, which are 40.0 percent of the contracts behind the deposit-inclusive index and whose log rent correlates 0.920 with the baseline, gives a pooled slope of −1.045 (0.236) and a capital-minus-noncapital difference of −1.588 (0.337): smaller with deposits included, same sign. Housing-type-specific indices give a negative capital-region slope for every type, from −0.843 for apartments to −2.194 for single- and multi-family houses, and no noncapital slope distinguishable from zero. Lowering the contract threshold from 20 to 10 or 5 enlarges the choice sets to 220–225 and 225–228 municipalities and leaves the pooled slope at −1.150 and the difference at −1.976 and −1.968. Bins or a quadratic in log distance leave the pooled slope at −1.021 and −1.125.</p>
<p>The last check concerns who is in the sample. Wage workers are 54.3 to 58.1 percent of persons aged 19–34 across the seven half-years, so the choice sample omits about two-fifths of the age group — necessarily, since a nonemployed person has no workplace to condition on. A survey-weighted multinomial logit on 409,456 persons aged 19–34, distinguishing nonemployment, other employment and wage employment, has an AUC of 0.725 for wage employment; residence attributes barely separate the groups, with a coefficient of 0.004 (p = 0.855) on standardized residence rent. Stabilized inverse-probability weights clipped at the 1st and 99th percentiles reduce the effective sample size from 172,221 to 135,009 and the largest standardized mean difference from 0.333 to 0.035.</p>
<table class="caption-top table">
<caption>Reweighting wage workers toward all persons aged 19–34 on observed characteristics. Under the 1st/99th weights the residence-block wild-score interval for the between slope is [−1.655, −0.870].</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Weighting</th>
<th style="text-align: right;">Between-municipality slope</th>
<th style="text-align: right;">Capital-workplace contrast</th>
<th style="text-align: right;">Effective sample size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Analysis weights</td>
<td style="text-align: right;">−1.254 (0.281)</td>
<td style="text-align: right;">−5.531 (1.206)</td>
<td style="text-align: right;">172,221</td>
</tr>
<tr class="even">
<td style="text-align: left;">IPW, clipped at 1st/99th percentiles</td>
<td style="text-align: right;">−1.265 (0.283)</td>
<td style="text-align: right;">−6.028 (1.144)</td>
<td style="text-align: right;">135,009</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IPW, clipped at 5th/95th percentiles</td>
<td style="text-align: right;">−1.261 (0.282)</td>
<td style="text-align: right;">−5.924 (1.151)</td>
<td style="text-align: right;">149,235</td>
</tr>
<tr class="even">
<td style="text-align: left;">Overlap weights</td>
<td style="text-align: right;">−1.270 (0.282)</td>
<td style="text-align: right;">n.a.</td>
<td style="text-align: right;">155,081</td>
</tr>
</tbody>
</table>
<p>The spatial estimates barely move. The exercise is narrower than a correction — the weights balance observed characteristics only, cannot give a nonemployed person a potential workplace, and rest on no exclusion restriction — so selection on unobservables is untouched, and the results remain statements about employed wage workers aged 19–34. That is why the paper’s scope is defined that way.</p>
</section>
<section id="the-boundary-of-what-the-current-evidence-supports" class="level2">
<h2 class="anchored" data-anchor-id="the-boundary-of-what-the-current-evidence-supports">9. The boundary of what the current evidence supports</h2>
<p><strong>Established.</strong> Conditional on the workplace, a residence municipality with persistently higher standardized rent is chosen less often by young wage workers, and the gradient — −1.153 pooled, −1.254 between municipalities — does not depend on sampled alternatives, random seeds, any single half-year, or the inference method. It arises from persistent differences in rent levels between municipalities, not from changes within them, and it is confined to capital-region residences: the capital-minus-noncapital contrast of −2.166 remains −1.903 after the commuter cities are removed, and across noncapital residences no gradient is detected. Workers at high-rent workplace centres have a rent slope steeper by −1.501, more often live in a municipality cheaper than their workplace, and commute longer.</p>
<p><strong>Ruled out.</strong> That the gradient is an artefact of sampled choice sets, of a single survey round, or of the rent measure. That it reflects municipal job access, expected wages, or static small-unit housing supply, at the resolution these can be measured. That the sharp contrast among capital-region workers (−5.531) shows capital-workplace commuters avoiding high rent: it rests on five adjacent noncapital cities, and its difference-in-differences is indistinguishable from zero once they are removed. That reweighting on observed employment selection overturns any of the gradients.</p>
<p><strong>Still admissible.</strong> That rent changes within a municipality matter for residential choice: seven half-years give the within coefficient too little variation to say. That the capital-region gradient holds across the full rent distribution: on common support it keeps its sign, but on a fifth of the capital region’s cells. That unobserved taste heterogeneity, which the conditional logit’s independence of irrelevant alternatives does not model, shapes the substitution among residences — removing Seoul, Incheon or Gyeonggi in turn leaves the contrast close to its full-choice value, but that is a stability check rather than a model of heterogeneity. And that the demographic differences reported as null are real but small.</p>
<p><strong>Unresolved.</strong> What the gradient would be as a causal response to rent, since the design uses no exogenous variation and rent remains an equilibrium price carrying unobserved quality, supply and sorting. What individual workers actually pay, since the index is the market rent of a standardized small unit rather than the worker’s own contract or rent-to-income burden. And how the joint choice of workplace and residence is made, since the workplace is conditioned on rather than chosen.</p>
</section>
<section id="what-would-move-this-forward" class="level2">
<h2 class="anchored" data-anchor-id="what-would-move-this-forward">10. What would move this forward</h2>
<p>None of the limits above would be removed by more half-years of the same survey. Each points to a different source of information.</p>
<p><strong>Panel identifiers.</strong> Where survey rounds can be linked at the person level, the analysis could follow workers across rounds and describe moves rather than distributions of residences.</p>
<p><strong>Discrete supply events.</strong> Large-scale completions of small units near expensive workplace centres are the kind of variation that would let the conditional associations here be read as responses to a change in housing supply.</p>
<p><strong>The tenure margin.</strong> Korean young renters choose between deposit-only and monthly-rent contracts, and the deposit-inclusive index moves the gradients without changing their sign; a model of that choice would say how much of the gradient is a choice of tenure rather than of place.</p>
<p><strong>Substitution structure.</strong> Nested or mixed logit specifications would relax the independence of irrelevant alternatives across residences and let the capital-region result be read as a pattern of substitution among municipalities rather than a difference in slopes.</p>
<p><strong>Travel time and the worker’s own rent.</strong> Centroid distance is a coarse proxy for commuting cost, especially within large cities, and the standardized index is not what a given worker pays. Route-based travel time and linked rent records would replace both proxies with the quantities the model is about.</p>
</section>
<section id="working-paper" class="level2">
<h2 class="anchored" data-anchor-id="working-paper">Working paper</h2>
<p>The working paper reports the full estimating equations, the construction of the rent index and its comparison with published rent series, the bridge between survey, lease and boundary geographies, the complete set of robustness checks including the deposit-inclusive index and the alternative distance forms, and the employment-selection reweighting, in 6 tables and 7 figures in the text and 9 tables and 3 figures in the appendix.</p>
<p><a href="https://khdouble.github.io/files/wp/cheaper-but-farther-rent-gradients-commuting-korea.pdf">Download the PDF</a></p>
<section id="suggested-citation" class="level3">
<h3 class="anchored" data-anchor-id="suggested-citation">Suggested citation</h3>
<blockquote class="blockquote">
<p>Kim, Hyun Hak (2026). “Cheaper but Farther: Rent Gradients and Commuting in the Residential Choices of Young Korean Workers.” Working Paper, September 20.</p>
</blockquote>
</section>
<section id="data-and-code" class="level3">
<h3 class="anchored" data-anchor-id="data-and-code">Data and code</h3>
<p>The analysis links restricted and public sources. Worker microdata are the Regional Employment Survey of Statistics Korea, obtained through its <a href="https://mdis.kostat.go.kr">Microdata Integrated Service</a> under access conditions that do not permit redistribution. Lease contracts come from the Real Transaction Management System of the Ministry of Land, Infrastructure and Transport, youth job openings from Work24 of the Ministry of Employment and Labor, local service indicators from the e-Local Indicators of the Korean Statistical Information Service, and municipality boundaries and centroids from the Statistical Geographic Information Service; all are public.</p>
<p>The municipality-half-year rent index, the derived choice-set tables, the ledger that documents every reported figure, and the estimation code will be deposited in a public repository with the published version of the paper. Until then, requests for academic replication or verification are handled individually. Please write to <a href="mailto:hyunhak.kim@kookmin.ac.kr">hyunhak.kim@kookmin.ac.kr</a>.</p>
</section>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<p>Cameron, A. C., Gelbach, J. B. and Miller, D. L. (2011). Robust inference with multiway clustering. <em>Journal of Business &amp; Economic Statistics</em>, 29(2), 238–249.</p>
<p>Ganong, P. and Shoag, D. (2017). Why has regional income convergence in the U.S. declined? <em>Journal of Urban Economics</em>, 102, 76–90.</p>
<p>Glaeser, E. L. and Gottlieb, J. D. (2009). The wealth of cities: agglomeration economies and spatial equilibrium in the United States. <em>Journal of Economic Literature</em>, 47(4), 983–1028.</p>
<p>Hsieh, C.-T. and Moretti, E. (2019). Housing constraints and spatial misallocation. <em>American Economic Journal: Macroeconomics</em>, 11(2), 1–39.</p>
<p>Kline, P. and Santos, A. (2012). A score based approach to wild bootstrap inference. <em>Journal of Econometric Methods</em>, 1(1), 23–41.</p>
<p>McFadden, D. (1974). Conditional logit analysis of qualitative choice behavior. In P. Zarembka (ed.), <em>Frontiers in Econometrics</em>, 105–142. Academic Press.</p>
<p>McFadden, D. (1978). Modeling the choice of residential location. <em>Transportation Research Record</em>, 673, 72–77.</p>
<p>Roback, J. (1982). Wages, rents, and the quality of life. <em>Journal of Political Economy</em>, 90(6), 1257–1278.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/khdouble\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© Hyun Hak Kim · Department of Economics, Kookmin University</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>